// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qrf_magnitude_float_s (
        ap_clk,
        ap_rst,
        a_M_real,
        a_M_imag,
        b_M_real,
        b_M_imag,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] a_M_real;
input  [31:0] a_M_imag;
input  [31:0] b_M_real;
input  [31:0] b_M_imag;
output  [31:0] ap_return;
input   ap_ce;

wire   [31:0] d1_4_fu_175_p1;
reg   [31:0] d1_4_reg_605;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
wire    ap_block_state40_pp0_stage0_iter39;
wire    ap_block_state41_pp0_stage0_iter40;
wire    ap_block_state42_pp0_stage0_iter41;
wire    ap_block_state43_pp0_stage0_iter42;
wire    ap_block_state44_pp0_stage0_iter43;
wire    ap_block_state45_pp0_stage0_iter44;
wire    ap_block_state46_pp0_stage0_iter45;
wire    ap_block_state47_pp0_stage0_iter46;
wire    ap_block_state48_pp0_stage0_iter47;
wire    ap_block_state49_pp0_stage0_iter48;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] d1_4_reg_605_pp0_iter1_reg;
wire   [31:0] d2_4_fu_204_p1;
reg   [31:0] d2_4_reg_617;
reg   [31:0] d2_4_reg_617_pp0_iter1_reg;
wire   [31:0] largest_4_fu_233_p1;
reg   [31:0] largest_4_reg_629;
reg   [31:0] largest_4_reg_629_pp0_iter1_reg;
wire   [31:0] d3_fu_262_p1;
reg   [31:0] d3_reg_642;
reg   [31:0] d3_reg_642_pp0_iter1_reg;
wire   [0:0] or_ln179_fu_301_p2;
reg   [0:0] or_ln179_reg_653;
wire   [0:0] or_ln179_1_fu_319_p2;
reg   [0:0] or_ln179_1_reg_660;
wire   [0:0] or_ln179_2_fu_347_p2;
reg   [0:0] or_ln179_2_reg_667;
wire   [0:0] or_ln179_3_fu_375_p2;
reg   [0:0] or_ln179_3_reg_674;
wire   [0:0] and_ln179_1_fu_417_p2;
reg   [0:0] and_ln179_1_reg_681;
wire   [0:0] and_ln189_1_fu_477_p2;
reg   [0:0] and_ln189_1_reg_689;
wire   [0:0] and_ln184_7_fu_501_p2;
reg   [0:0] and_ln184_7_reg_695;
wire   [31:0] d1_3_fu_522_p3;
reg   [31:0] d1_3_reg_703;
wire   [31:0] d2_3_fu_533_p3;
reg   [31:0] d2_3_reg_708;
wire   [31:0] d3_3_fu_545_p3;
reg   [31:0] d3_3_reg_713;
wire   [31:0] largest_3_fu_557_p3;
reg   [31:0] largest_3_reg_718;
reg   [31:0] largest_3_reg_718_pp0_iter3_reg;
reg   [31:0] largest_3_reg_718_pp0_iter4_reg;
reg   [31:0] largest_3_reg_718_pp0_iter5_reg;
reg   [31:0] largest_3_reg_718_pp0_iter6_reg;
reg   [31:0] largest_3_reg_718_pp0_iter7_reg;
reg   [31:0] largest_3_reg_718_pp0_iter8_reg;
reg   [31:0] largest_3_reg_718_pp0_iter9_reg;
reg   [31:0] largest_3_reg_718_pp0_iter10_reg;
reg   [31:0] largest_3_reg_718_pp0_iter11_reg;
reg   [31:0] largest_3_reg_718_pp0_iter12_reg;
reg   [31:0] largest_3_reg_718_pp0_iter13_reg;
reg   [31:0] largest_3_reg_718_pp0_iter14_reg;
reg   [31:0] largest_3_reg_718_pp0_iter15_reg;
reg   [31:0] largest_3_reg_718_pp0_iter16_reg;
reg   [31:0] largest_3_reg_718_pp0_iter17_reg;
reg   [31:0] largest_3_reg_718_pp0_iter18_reg;
reg   [31:0] largest_3_reg_718_pp0_iter19_reg;
reg   [31:0] largest_3_reg_718_pp0_iter20_reg;
reg   [31:0] largest_3_reg_718_pp0_iter21_reg;
reg   [31:0] largest_3_reg_718_pp0_iter22_reg;
reg   [31:0] largest_3_reg_718_pp0_iter23_reg;
reg   [31:0] largest_3_reg_718_pp0_iter24_reg;
reg   [31:0] largest_3_reg_718_pp0_iter25_reg;
reg   [31:0] largest_3_reg_718_pp0_iter26_reg;
reg   [31:0] largest_3_reg_718_pp0_iter27_reg;
reg   [31:0] largest_3_reg_718_pp0_iter28_reg;
reg   [31:0] largest_3_reg_718_pp0_iter29_reg;
reg   [31:0] largest_3_reg_718_pp0_iter30_reg;
reg   [31:0] largest_3_reg_718_pp0_iter31_reg;
reg   [31:0] largest_3_reg_718_pp0_iter32_reg;
reg   [31:0] largest_3_reg_718_pp0_iter33_reg;
reg   [31:0] largest_3_reg_718_pp0_iter34_reg;
reg   [31:0] largest_3_reg_718_pp0_iter35_reg;
reg   [31:0] largest_3_reg_718_pp0_iter36_reg;
reg   [31:0] largest_3_reg_718_pp0_iter37_reg;
reg   [31:0] largest_3_reg_718_pp0_iter38_reg;
reg   [31:0] largest_3_reg_718_pp0_iter39_reg;
reg   [31:0] largest_3_reg_718_pp0_iter40_reg;
reg   [31:0] largest_3_reg_718_pp0_iter41_reg;
reg   [31:0] largest_3_reg_718_pp0_iter42_reg;
reg   [31:0] largest_3_reg_718_pp0_iter43_reg;
reg   [31:0] largest_3_reg_718_pp0_iter44_reg;
wire   [0:0] and_ln201_fu_599_p2;
reg   [0:0] and_ln201_reg_728;
reg   [0:0] and_ln201_reg_728_pp0_iter4_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter5_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter6_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter7_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter8_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter9_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter10_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter11_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter12_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter13_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter14_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter15_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter16_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter17_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter18_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter19_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter20_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter21_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter22_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter23_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter24_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter25_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter26_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter27_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter28_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter29_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter30_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter31_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter32_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter33_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter34_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter35_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter36_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter37_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter38_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter39_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter40_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter41_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter42_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter43_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter44_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter45_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter46_reg;
reg   [0:0] and_ln201_reg_728_pp0_iter47_reg;
wire   [31:0] grp_fu_97_p2;
reg   [31:0] x1_reg_732;
wire   [31:0] grp_fu_101_p2;
reg   [31:0] x2_reg_738;
wire   [31:0] grp_fu_105_p2;
reg   [31:0] x3_reg_744;
wire   [31:0] grp_fu_80_p2;
reg   [31:0] x1_sqd_reg_750;
wire   [31:0] grp_fu_84_p2;
reg   [31:0] x2_sqd_reg_755;
wire   [31:0] grp_fu_88_p2;
reg   [31:0] x3_sqd_reg_760;
wire   [31:0] grp_fu_67_p2;
reg   [31:0] s1_reg_765;
wire   [31:0] grp_fu_72_p2;
reg   [31:0] s2_reg_770;
wire   [31:0] grp_fu_76_p2;
reg   [31:0] s3_reg_775;
wire   [31:0] grp_fu_150_p2;
reg   [31:0] tmp_i_i_reg_780;
reg   [31:0] ap_phi_mux_p_0_phi_fu_60_p4;
wire   [31:0] grp_fu_92_p2;
reg   [31:0] ap_phi_reg_pp0_iter48_p_0_reg_56;
wire    ap_block_pp0_stage0;
wire   [31:0] ap_phi_reg_pp0_iter0_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter1_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter2_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter3_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter4_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter5_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter6_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter7_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter8_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter9_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter10_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter11_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter12_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter13_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter14_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter15_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter16_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter17_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter18_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter19_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter20_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter21_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter22_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter23_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter24_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter25_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter26_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter27_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter28_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter29_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter30_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter31_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter32_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter33_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter34_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter35_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter36_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter37_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter38_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter39_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter40_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter41_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter42_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter43_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter44_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter45_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter46_p_0_reg_56;
reg   [31:0] ap_phi_reg_pp0_iter47_p_0_reg_56;
wire   [31:0] grp_fu_145_p0;
wire   [31:0] p_Val2_s_fu_155_p1;
wire   [30:0] trunc_ln368_fu_159_p1;
wire   [31:0] p_Result_s_fu_167_p3;
wire   [31:0] p_Val2_64_fu_184_p1;
wire   [30:0] trunc_ln368_1_fu_188_p1;
wire   [31:0] p_Result_48_fu_196_p3;
wire   [31:0] p_Val2_65_fu_213_p1;
wire   [30:0] trunc_ln368_2_fu_217_p1;
wire   [31:0] p_Result_49_fu_225_p3;
wire   [31:0] p_Val2_66_fu_242_p1;
wire   [30:0] trunc_ln368_3_fu_246_p1;
wire   [31:0] p_Result_50_fu_254_p3;
wire   [7:0] tmp_1_fu_269_p4;
wire   [22:0] trunc_ln189_fu_163_p1;
wire   [0:0] icmp_ln179_1_fu_295_p2;
wire   [0:0] icmp_ln179_fu_289_p2;
wire   [7:0] tmp_2_fu_279_p4;
wire   [22:0] trunc_ln189_1_fu_192_p1;
wire   [0:0] icmp_ln179_3_fu_313_p2;
wire   [0:0] icmp_ln179_2_fu_307_p2;
wire   [7:0] tmp_4_fu_325_p4;
wire   [22:0] trunc_ln189_2_fu_221_p1;
wire   [0:0] icmp_ln179_5_fu_341_p2;
wire   [0:0] icmp_ln179_4_fu_335_p2;
wire   [7:0] tmp_6_fu_353_p4;
wire   [22:0] trunc_ln189_3_fu_250_p1;
wire   [0:0] icmp_ln179_7_fu_369_p2;
wire   [0:0] icmp_ln179_6_fu_363_p2;
wire   [0:0] and_ln179_fu_381_p2;
wire   [0:0] grp_fu_109_p2;
wire   [0:0] and_ln179_3_fu_391_p2;
wire   [0:0] grp_fu_113_p2;
wire   [0:0] and_ln179_5_fu_401_p2;
wire   [0:0] grp_fu_117_p2;
wire   [0:0] and_ln179_4_fu_395_p2;
wire   [0:0] and_ln179_6_fu_405_p2;
wire   [0:0] and_ln179_7_fu_411_p2;
wire   [0:0] and_ln179_2_fu_385_p2;
wire   [0:0] grp_fu_121_p2;
wire   [0:0] and_ln184_1_fu_429_p2;
wire   [0:0] grp_fu_125_p2;
wire   [0:0] and_ln184_3_fu_439_p2;
wire   [0:0] grp_fu_129_p2;
wire   [0:0] grp_fu_133_p2;
wire   [0:0] grp_fu_137_p2;
wire   [0:0] and_ln189_3_fu_461_p2;
wire   [0:0] grp_fu_141_p2;
wire   [0:0] and_ln189_2_fu_455_p2;
wire   [0:0] and_ln189_4_fu_465_p2;
wire   [0:0] and_ln189_5_fu_471_p2;
wire   [0:0] and_ln189_fu_449_p2;
wire   [0:0] and_ln184_2_fu_433_p2;
wire   [0:0] and_ln184_4_fu_443_p2;
wire   [0:0] and_ln184_fu_423_p2;
wire   [0:0] xor_ln179_fu_483_p2;
wire   [0:0] and_ln184_6_fu_495_p2;
wire   [0:0] and_ln184_5_fu_489_p2;
wire   [31:0] d1_fu_517_p3;
wire   [31:0] d2_fu_528_p3;
wire   [31:0] d3_1_fu_507_p3;
wire   [31:0] d3_2_fu_539_p3;
wire   [31:0] largest_1_fu_512_p3;
wire   [31:0] largest_2_fu_551_p3;
wire   [31:0] bitcast_ln201_fu_564_p1;
wire   [7:0] tmp_14_fu_567_p4;
wire   [22:0] trunc_ln201_fu_577_p1;
wire   [0:0] icmp_ln201_1_fu_587_p2;
wire   [0:0] icmp_ln201_fu_581_p2;
wire   [0:0] or_ln201_fu_593_p2;
wire   [0:0] grp_fu_145_p2;
reg    grp_fu_67_ce;
reg    grp_fu_72_ce;
reg    grp_fu_76_ce;
reg    grp_fu_80_ce;
reg    grp_fu_84_ce;
reg    grp_fu_88_ce;
reg    grp_fu_92_ce;
reg    grp_fu_97_ce;
reg    grp_fu_101_ce;
reg    grp_fu_105_ce;
reg    grp_fu_109_ce;
wire    ap_block_pp0_stage0_00001;
reg    grp_fu_113_ce;
reg    grp_fu_117_ce;
reg    grp_fu_121_ce;
reg    grp_fu_125_ce;
reg    grp_fu_129_ce;
reg    grp_fu_133_ce;
reg    grp_fu_137_ce;
reg    grp_fu_141_ce;
reg    grp_fu_145_ce;
reg    grp_fu_150_ce;
reg   [31:0] a_M_real_int_reg;
reg   [31:0] a_M_imag_int_reg;
reg   [31:0] b_M_real_int_reg;
reg   [31:0] b_M_imag_int_reg;

music_fadd_32ns_3ocq #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fadd_32ns_3ocq_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x1_sqd_reg_750),
    .din1(32'd1065353216),
    .ce(grp_fu_67_ce),
    .dout(grp_fu_67_p2)
);

music_fadd_32ns_3ocq #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fadd_32ns_3ocq_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x2_sqd_reg_755),
    .din1(x3_sqd_reg_760),
    .ce(grp_fu_72_ce),
    .dout(grp_fu_72_p2)
);

music_fadd_32ns_3ocq #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fadd_32ns_3ocq_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(s1_reg_765),
    .din1(s2_reg_770),
    .ce(grp_fu_76_ce),
    .dout(grp_fu_76_p2)
);

music_fmul_32ns_3jbC #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fmul_32ns_3jbC_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x1_reg_732),
    .din1(x1_reg_732),
    .ce(grp_fu_80_ce),
    .dout(grp_fu_80_p2)
);

music_fmul_32ns_3jbC #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fmul_32ns_3jbC_U57(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x2_reg_738),
    .din1(x2_reg_738),
    .ce(grp_fu_84_ce),
    .dout(grp_fu_84_p2)
);

music_fmul_32ns_3jbC #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fmul_32ns_3jbC_U58(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x3_reg_744),
    .din1(x3_reg_744),
    .ce(grp_fu_88_ce),
    .dout(grp_fu_88_p2)
);

music_fmul_32ns_3jbC #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fmul_32ns_3jbC_U59(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(largest_3_reg_718_pp0_iter44_reg),
    .din1(tmp_i_i_reg_780),
    .ce(grp_fu_92_ce),
    .dout(grp_fu_92_p2)
);

music_fdiv_32ns_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fdiv_32ns_3ncg_U60(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d1_3_reg_703),
    .din1(largest_3_reg_718),
    .ce(grp_fu_97_ce),
    .dout(grp_fu_97_p2)
);

music_fdiv_32ns_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fdiv_32ns_3ncg_U61(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d2_3_reg_708),
    .din1(largest_3_reg_718),
    .ce(grp_fu_101_ce),
    .dout(grp_fu_101_p2)
);

music_fdiv_32ns_3ncg #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fdiv_32ns_3ncg_U62(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d3_3_reg_713),
    .din1(largest_3_reg_718),
    .ce(grp_fu_105_ce),
    .dout(grp_fu_105_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U63(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d1_4_fu_175_p1),
    .din1(d2_4_fu_204_p1),
    .ce(grp_fu_109_ce),
    .opcode(5'd2),
    .dout(grp_fu_109_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U64(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d1_4_fu_175_p1),
    .din1(largest_4_fu_233_p1),
    .ce(grp_fu_113_ce),
    .opcode(5'd2),
    .dout(grp_fu_113_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d1_4_fu_175_p1),
    .din1(d3_fu_262_p1),
    .ce(grp_fu_117_ce),
    .opcode(5'd2),
    .dout(grp_fu_117_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d2_4_fu_204_p1),
    .din1(d1_4_fu_175_p1),
    .ce(grp_fu_121_ce),
    .opcode(5'd2),
    .dout(grp_fu_121_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d2_4_fu_204_p1),
    .din1(largest_4_fu_233_p1),
    .ce(grp_fu_125_ce),
    .opcode(5'd2),
    .dout(grp_fu_125_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U68(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(d2_4_fu_204_p1),
    .din1(d3_fu_262_p1),
    .ce(grp_fu_129_ce),
    .opcode(5'd2),
    .dout(grp_fu_129_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U69(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(largest_4_fu_233_p1),
    .din1(d1_4_fu_175_p1),
    .ce(grp_fu_133_ce),
    .opcode(5'd2),
    .dout(grp_fu_133_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U70(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(largest_4_fu_233_p1),
    .din1(d2_4_fu_204_p1),
    .ce(grp_fu_137_ce),
    .opcode(5'd2),
    .dout(grp_fu_137_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U71(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(largest_4_fu_233_p1),
    .din1(d3_fu_262_p1),
    .ce(grp_fu_141_ce),
    .opcode(5'd2),
    .dout(grp_fu_141_p2)
);

music_fcmp_32ns_3pcA #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
music_fcmp_32ns_3pcA_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_145_p0),
    .din1(32'd0),
    .ce(grp_fu_145_ce),
    .opcode(5'd1),
    .dout(grp_fu_145_p2)
);

music_fsqrt_32ns_qcK #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
music_fsqrt_32ns_qcK_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(s3_reg_775),
    .ce(grp_fu_150_ce),
    .dout(grp_fu_150_p2)
);

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        if ((1'd1 == and_ln201_fu_599_p2)) begin
            ap_phi_reg_pp0_iter4_p_0_reg_56 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_p_0_reg_56 <= ap_phi_reg_pp0_iter3_p_0_reg_56;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        a_M_imag_int_reg <= a_M_imag;
        a_M_real_int_reg <= a_M_real;
        b_M_imag_int_reg <= b_M_imag;
        b_M_real_int_reg <= b_M_real;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        and_ln179_1_reg_681 <= and_ln179_1_fu_417_p2;
        and_ln184_7_reg_695 <= and_ln184_7_fu_501_p2;
        and_ln189_1_reg_689 <= and_ln189_1_fu_477_p2;
        and_ln201_reg_728 <= and_ln201_fu_599_p2;
        and_ln201_reg_728_pp0_iter10_reg <= and_ln201_reg_728_pp0_iter9_reg;
        and_ln201_reg_728_pp0_iter11_reg <= and_ln201_reg_728_pp0_iter10_reg;
        and_ln201_reg_728_pp0_iter12_reg <= and_ln201_reg_728_pp0_iter11_reg;
        and_ln201_reg_728_pp0_iter13_reg <= and_ln201_reg_728_pp0_iter12_reg;
        and_ln201_reg_728_pp0_iter14_reg <= and_ln201_reg_728_pp0_iter13_reg;
        and_ln201_reg_728_pp0_iter15_reg <= and_ln201_reg_728_pp0_iter14_reg;
        and_ln201_reg_728_pp0_iter16_reg <= and_ln201_reg_728_pp0_iter15_reg;
        and_ln201_reg_728_pp0_iter17_reg <= and_ln201_reg_728_pp0_iter16_reg;
        and_ln201_reg_728_pp0_iter18_reg <= and_ln201_reg_728_pp0_iter17_reg;
        and_ln201_reg_728_pp0_iter19_reg <= and_ln201_reg_728_pp0_iter18_reg;
        and_ln201_reg_728_pp0_iter20_reg <= and_ln201_reg_728_pp0_iter19_reg;
        and_ln201_reg_728_pp0_iter21_reg <= and_ln201_reg_728_pp0_iter20_reg;
        and_ln201_reg_728_pp0_iter22_reg <= and_ln201_reg_728_pp0_iter21_reg;
        and_ln201_reg_728_pp0_iter23_reg <= and_ln201_reg_728_pp0_iter22_reg;
        and_ln201_reg_728_pp0_iter24_reg <= and_ln201_reg_728_pp0_iter23_reg;
        and_ln201_reg_728_pp0_iter25_reg <= and_ln201_reg_728_pp0_iter24_reg;
        and_ln201_reg_728_pp0_iter26_reg <= and_ln201_reg_728_pp0_iter25_reg;
        and_ln201_reg_728_pp0_iter27_reg <= and_ln201_reg_728_pp0_iter26_reg;
        and_ln201_reg_728_pp0_iter28_reg <= and_ln201_reg_728_pp0_iter27_reg;
        and_ln201_reg_728_pp0_iter29_reg <= and_ln201_reg_728_pp0_iter28_reg;
        and_ln201_reg_728_pp0_iter30_reg <= and_ln201_reg_728_pp0_iter29_reg;
        and_ln201_reg_728_pp0_iter31_reg <= and_ln201_reg_728_pp0_iter30_reg;
        and_ln201_reg_728_pp0_iter32_reg <= and_ln201_reg_728_pp0_iter31_reg;
        and_ln201_reg_728_pp0_iter33_reg <= and_ln201_reg_728_pp0_iter32_reg;
        and_ln201_reg_728_pp0_iter34_reg <= and_ln201_reg_728_pp0_iter33_reg;
        and_ln201_reg_728_pp0_iter35_reg <= and_ln201_reg_728_pp0_iter34_reg;
        and_ln201_reg_728_pp0_iter36_reg <= and_ln201_reg_728_pp0_iter35_reg;
        and_ln201_reg_728_pp0_iter37_reg <= and_ln201_reg_728_pp0_iter36_reg;
        and_ln201_reg_728_pp0_iter38_reg <= and_ln201_reg_728_pp0_iter37_reg;
        and_ln201_reg_728_pp0_iter39_reg <= and_ln201_reg_728_pp0_iter38_reg;
        and_ln201_reg_728_pp0_iter40_reg <= and_ln201_reg_728_pp0_iter39_reg;
        and_ln201_reg_728_pp0_iter41_reg <= and_ln201_reg_728_pp0_iter40_reg;
        and_ln201_reg_728_pp0_iter42_reg <= and_ln201_reg_728_pp0_iter41_reg;
        and_ln201_reg_728_pp0_iter43_reg <= and_ln201_reg_728_pp0_iter42_reg;
        and_ln201_reg_728_pp0_iter44_reg <= and_ln201_reg_728_pp0_iter43_reg;
        and_ln201_reg_728_pp0_iter45_reg <= and_ln201_reg_728_pp0_iter44_reg;
        and_ln201_reg_728_pp0_iter46_reg <= and_ln201_reg_728_pp0_iter45_reg;
        and_ln201_reg_728_pp0_iter47_reg <= and_ln201_reg_728_pp0_iter46_reg;
        and_ln201_reg_728_pp0_iter4_reg <= and_ln201_reg_728;
        and_ln201_reg_728_pp0_iter5_reg <= and_ln201_reg_728_pp0_iter4_reg;
        and_ln201_reg_728_pp0_iter6_reg <= and_ln201_reg_728_pp0_iter5_reg;
        and_ln201_reg_728_pp0_iter7_reg <= and_ln201_reg_728_pp0_iter6_reg;
        and_ln201_reg_728_pp0_iter8_reg <= and_ln201_reg_728_pp0_iter7_reg;
        and_ln201_reg_728_pp0_iter9_reg <= and_ln201_reg_728_pp0_iter8_reg;
        ap_phi_reg_pp0_iter10_p_0_reg_56 <= ap_phi_reg_pp0_iter9_p_0_reg_56;
        ap_phi_reg_pp0_iter11_p_0_reg_56 <= ap_phi_reg_pp0_iter10_p_0_reg_56;
        ap_phi_reg_pp0_iter12_p_0_reg_56 <= ap_phi_reg_pp0_iter11_p_0_reg_56;
        ap_phi_reg_pp0_iter13_p_0_reg_56 <= ap_phi_reg_pp0_iter12_p_0_reg_56;
        ap_phi_reg_pp0_iter14_p_0_reg_56 <= ap_phi_reg_pp0_iter13_p_0_reg_56;
        ap_phi_reg_pp0_iter15_p_0_reg_56 <= ap_phi_reg_pp0_iter14_p_0_reg_56;
        ap_phi_reg_pp0_iter16_p_0_reg_56 <= ap_phi_reg_pp0_iter15_p_0_reg_56;
        ap_phi_reg_pp0_iter17_p_0_reg_56 <= ap_phi_reg_pp0_iter16_p_0_reg_56;
        ap_phi_reg_pp0_iter18_p_0_reg_56 <= ap_phi_reg_pp0_iter17_p_0_reg_56;
        ap_phi_reg_pp0_iter19_p_0_reg_56 <= ap_phi_reg_pp0_iter18_p_0_reg_56;
        ap_phi_reg_pp0_iter1_p_0_reg_56 <= ap_phi_reg_pp0_iter0_p_0_reg_56;
        ap_phi_reg_pp0_iter20_p_0_reg_56 <= ap_phi_reg_pp0_iter19_p_0_reg_56;
        ap_phi_reg_pp0_iter21_p_0_reg_56 <= ap_phi_reg_pp0_iter20_p_0_reg_56;
        ap_phi_reg_pp0_iter22_p_0_reg_56 <= ap_phi_reg_pp0_iter21_p_0_reg_56;
        ap_phi_reg_pp0_iter23_p_0_reg_56 <= ap_phi_reg_pp0_iter22_p_0_reg_56;
        ap_phi_reg_pp0_iter24_p_0_reg_56 <= ap_phi_reg_pp0_iter23_p_0_reg_56;
        ap_phi_reg_pp0_iter25_p_0_reg_56 <= ap_phi_reg_pp0_iter24_p_0_reg_56;
        ap_phi_reg_pp0_iter26_p_0_reg_56 <= ap_phi_reg_pp0_iter25_p_0_reg_56;
        ap_phi_reg_pp0_iter27_p_0_reg_56 <= ap_phi_reg_pp0_iter26_p_0_reg_56;
        ap_phi_reg_pp0_iter28_p_0_reg_56 <= ap_phi_reg_pp0_iter27_p_0_reg_56;
        ap_phi_reg_pp0_iter29_p_0_reg_56 <= ap_phi_reg_pp0_iter28_p_0_reg_56;
        ap_phi_reg_pp0_iter2_p_0_reg_56 <= ap_phi_reg_pp0_iter1_p_0_reg_56;
        ap_phi_reg_pp0_iter30_p_0_reg_56 <= ap_phi_reg_pp0_iter29_p_0_reg_56;
        ap_phi_reg_pp0_iter31_p_0_reg_56 <= ap_phi_reg_pp0_iter30_p_0_reg_56;
        ap_phi_reg_pp0_iter32_p_0_reg_56 <= ap_phi_reg_pp0_iter31_p_0_reg_56;
        ap_phi_reg_pp0_iter33_p_0_reg_56 <= ap_phi_reg_pp0_iter32_p_0_reg_56;
        ap_phi_reg_pp0_iter34_p_0_reg_56 <= ap_phi_reg_pp0_iter33_p_0_reg_56;
        ap_phi_reg_pp0_iter35_p_0_reg_56 <= ap_phi_reg_pp0_iter34_p_0_reg_56;
        ap_phi_reg_pp0_iter36_p_0_reg_56 <= ap_phi_reg_pp0_iter35_p_0_reg_56;
        ap_phi_reg_pp0_iter37_p_0_reg_56 <= ap_phi_reg_pp0_iter36_p_0_reg_56;
        ap_phi_reg_pp0_iter38_p_0_reg_56 <= ap_phi_reg_pp0_iter37_p_0_reg_56;
        ap_phi_reg_pp0_iter39_p_0_reg_56 <= ap_phi_reg_pp0_iter38_p_0_reg_56;
        ap_phi_reg_pp0_iter3_p_0_reg_56 <= ap_phi_reg_pp0_iter2_p_0_reg_56;
        ap_phi_reg_pp0_iter40_p_0_reg_56 <= ap_phi_reg_pp0_iter39_p_0_reg_56;
        ap_phi_reg_pp0_iter41_p_0_reg_56 <= ap_phi_reg_pp0_iter40_p_0_reg_56;
        ap_phi_reg_pp0_iter42_p_0_reg_56 <= ap_phi_reg_pp0_iter41_p_0_reg_56;
        ap_phi_reg_pp0_iter43_p_0_reg_56 <= ap_phi_reg_pp0_iter42_p_0_reg_56;
        ap_phi_reg_pp0_iter44_p_0_reg_56 <= ap_phi_reg_pp0_iter43_p_0_reg_56;
        ap_phi_reg_pp0_iter45_p_0_reg_56 <= ap_phi_reg_pp0_iter44_p_0_reg_56;
        ap_phi_reg_pp0_iter46_p_0_reg_56 <= ap_phi_reg_pp0_iter45_p_0_reg_56;
        ap_phi_reg_pp0_iter47_p_0_reg_56 <= ap_phi_reg_pp0_iter46_p_0_reg_56;
        ap_phi_reg_pp0_iter48_p_0_reg_56 <= ap_phi_reg_pp0_iter47_p_0_reg_56;
        ap_phi_reg_pp0_iter5_p_0_reg_56 <= ap_phi_reg_pp0_iter4_p_0_reg_56;
        ap_phi_reg_pp0_iter6_p_0_reg_56 <= ap_phi_reg_pp0_iter5_p_0_reg_56;
        ap_phi_reg_pp0_iter7_p_0_reg_56 <= ap_phi_reg_pp0_iter6_p_0_reg_56;
        ap_phi_reg_pp0_iter8_p_0_reg_56 <= ap_phi_reg_pp0_iter7_p_0_reg_56;
        ap_phi_reg_pp0_iter9_p_0_reg_56 <= ap_phi_reg_pp0_iter8_p_0_reg_56;
        d1_3_reg_703[30 : 0] <= d1_3_fu_522_p3[30 : 0];
        d1_4_reg_605[30 : 0] <= d1_4_fu_175_p1[30 : 0];
        d1_4_reg_605_pp0_iter1_reg[30 : 0] <= d1_4_reg_605[30 : 0];
        d2_3_reg_708[30 : 0] <= d2_3_fu_533_p3[30 : 0];
        d2_4_reg_617[30 : 0] <= d2_4_fu_204_p1[30 : 0];
        d2_4_reg_617_pp0_iter1_reg[30 : 0] <= d2_4_reg_617[30 : 0];
        d3_3_reg_713[30 : 0] <= d3_3_fu_545_p3[30 : 0];
        d3_reg_642[30 : 0] <= d3_fu_262_p1[30 : 0];
        d3_reg_642_pp0_iter1_reg[30 : 0] <= d3_reg_642[30 : 0];
        largest_3_reg_718[30 : 0] <= largest_3_fu_557_p3[30 : 0];
        largest_3_reg_718_pp0_iter10_reg[30 : 0] <= largest_3_reg_718_pp0_iter9_reg[30 : 0];
        largest_3_reg_718_pp0_iter11_reg[30 : 0] <= largest_3_reg_718_pp0_iter10_reg[30 : 0];
        largest_3_reg_718_pp0_iter12_reg[30 : 0] <= largest_3_reg_718_pp0_iter11_reg[30 : 0];
        largest_3_reg_718_pp0_iter13_reg[30 : 0] <= largest_3_reg_718_pp0_iter12_reg[30 : 0];
        largest_3_reg_718_pp0_iter14_reg[30 : 0] <= largest_3_reg_718_pp0_iter13_reg[30 : 0];
        largest_3_reg_718_pp0_iter15_reg[30 : 0] <= largest_3_reg_718_pp0_iter14_reg[30 : 0];
        largest_3_reg_718_pp0_iter16_reg[30 : 0] <= largest_3_reg_718_pp0_iter15_reg[30 : 0];
        largest_3_reg_718_pp0_iter17_reg[30 : 0] <= largest_3_reg_718_pp0_iter16_reg[30 : 0];
        largest_3_reg_718_pp0_iter18_reg[30 : 0] <= largest_3_reg_718_pp0_iter17_reg[30 : 0];
        largest_3_reg_718_pp0_iter19_reg[30 : 0] <= largest_3_reg_718_pp0_iter18_reg[30 : 0];
        largest_3_reg_718_pp0_iter20_reg[30 : 0] <= largest_3_reg_718_pp0_iter19_reg[30 : 0];
        largest_3_reg_718_pp0_iter21_reg[30 : 0] <= largest_3_reg_718_pp0_iter20_reg[30 : 0];
        largest_3_reg_718_pp0_iter22_reg[30 : 0] <= largest_3_reg_718_pp0_iter21_reg[30 : 0];
        largest_3_reg_718_pp0_iter23_reg[30 : 0] <= largest_3_reg_718_pp0_iter22_reg[30 : 0];
        largest_3_reg_718_pp0_iter24_reg[30 : 0] <= largest_3_reg_718_pp0_iter23_reg[30 : 0];
        largest_3_reg_718_pp0_iter25_reg[30 : 0] <= largest_3_reg_718_pp0_iter24_reg[30 : 0];
        largest_3_reg_718_pp0_iter26_reg[30 : 0] <= largest_3_reg_718_pp0_iter25_reg[30 : 0];
        largest_3_reg_718_pp0_iter27_reg[30 : 0] <= largest_3_reg_718_pp0_iter26_reg[30 : 0];
        largest_3_reg_718_pp0_iter28_reg[30 : 0] <= largest_3_reg_718_pp0_iter27_reg[30 : 0];
        largest_3_reg_718_pp0_iter29_reg[30 : 0] <= largest_3_reg_718_pp0_iter28_reg[30 : 0];
        largest_3_reg_718_pp0_iter30_reg[30 : 0] <= largest_3_reg_718_pp0_iter29_reg[30 : 0];
        largest_3_reg_718_pp0_iter31_reg[30 : 0] <= largest_3_reg_718_pp0_iter30_reg[30 : 0];
        largest_3_reg_718_pp0_iter32_reg[30 : 0] <= largest_3_reg_718_pp0_iter31_reg[30 : 0];
        largest_3_reg_718_pp0_iter33_reg[30 : 0] <= largest_3_reg_718_pp0_iter32_reg[30 : 0];
        largest_3_reg_718_pp0_iter34_reg[30 : 0] <= largest_3_reg_718_pp0_iter33_reg[30 : 0];
        largest_3_reg_718_pp0_iter35_reg[30 : 0] <= largest_3_reg_718_pp0_iter34_reg[30 : 0];
        largest_3_reg_718_pp0_iter36_reg[30 : 0] <= largest_3_reg_718_pp0_iter35_reg[30 : 0];
        largest_3_reg_718_pp0_iter37_reg[30 : 0] <= largest_3_reg_718_pp0_iter36_reg[30 : 0];
        largest_3_reg_718_pp0_iter38_reg[30 : 0] <= largest_3_reg_718_pp0_iter37_reg[30 : 0];
        largest_3_reg_718_pp0_iter39_reg[30 : 0] <= largest_3_reg_718_pp0_iter38_reg[30 : 0];
        largest_3_reg_718_pp0_iter3_reg[30 : 0] <= largest_3_reg_718[30 : 0];
        largest_3_reg_718_pp0_iter40_reg[30 : 0] <= largest_3_reg_718_pp0_iter39_reg[30 : 0];
        largest_3_reg_718_pp0_iter41_reg[30 : 0] <= largest_3_reg_718_pp0_iter40_reg[30 : 0];
        largest_3_reg_718_pp0_iter42_reg[30 : 0] <= largest_3_reg_718_pp0_iter41_reg[30 : 0];
        largest_3_reg_718_pp0_iter43_reg[30 : 0] <= largest_3_reg_718_pp0_iter42_reg[30 : 0];
        largest_3_reg_718_pp0_iter44_reg[30 : 0] <= largest_3_reg_718_pp0_iter43_reg[30 : 0];
        largest_3_reg_718_pp0_iter4_reg[30 : 0] <= largest_3_reg_718_pp0_iter3_reg[30 : 0];
        largest_3_reg_718_pp0_iter5_reg[30 : 0] <= largest_3_reg_718_pp0_iter4_reg[30 : 0];
        largest_3_reg_718_pp0_iter6_reg[30 : 0] <= largest_3_reg_718_pp0_iter5_reg[30 : 0];
        largest_3_reg_718_pp0_iter7_reg[30 : 0] <= largest_3_reg_718_pp0_iter6_reg[30 : 0];
        largest_3_reg_718_pp0_iter8_reg[30 : 0] <= largest_3_reg_718_pp0_iter7_reg[30 : 0];
        largest_3_reg_718_pp0_iter9_reg[30 : 0] <= largest_3_reg_718_pp0_iter8_reg[30 : 0];
        largest_4_reg_629[30 : 0] <= largest_4_fu_233_p1[30 : 0];
        largest_4_reg_629_pp0_iter1_reg[30 : 0] <= largest_4_reg_629[30 : 0];
        or_ln179_1_reg_660 <= or_ln179_1_fu_319_p2;
        or_ln179_2_reg_667 <= or_ln179_2_fu_347_p2;
        or_ln179_3_reg_674 <= or_ln179_3_fu_375_p2;
        or_ln179_reg_653 <= or_ln179_fu_301_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln201_reg_728_pp0_iter26_reg) & (1'b1 == ap_ce))) begin
        s1_reg_765 <= grp_fu_67_p2;
        s2_reg_770 <= grp_fu_72_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln201_reg_728_pp0_iter31_reg) & (1'b1 == ap_ce))) begin
        s3_reg_775 <= grp_fu_76_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln201_reg_728_pp0_iter43_reg) & (1'b1 == ap_ce))) begin
        tmp_i_i_reg_780 <= grp_fu_150_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln201_reg_728_pp0_iter17_reg) & (1'b1 == ap_ce))) begin
        x1_reg_732 <= grp_fu_97_p2;
        x2_reg_738 <= grp_fu_101_p2;
        x3_reg_744 <= grp_fu_105_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln201_reg_728_pp0_iter21_reg) & (1'b1 == ap_ce))) begin
        x1_sqd_reg_750 <= grp_fu_80_p2;
        x2_sqd_reg_755 <= grp_fu_84_p2;
        x3_sqd_reg_760 <= grp_fu_88_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'd0 == and_ln201_reg_728_pp0_iter47_reg))) begin
        ap_phi_mux_p_0_phi_fu_60_p4 = grp_fu_92_p2;
    end else begin
        ap_phi_mux_p_0_phi_fu_60_p4 = ap_phi_reg_pp0_iter48_p_0_reg_56;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_101_ce = 1'b1;
    end else begin
        grp_fu_101_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_105_ce = 1'b1;
    end else begin
        grp_fu_105_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_109_ce = 1'b1;
    end else begin
        grp_fu_109_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_113_ce = 1'b1;
    end else begin
        grp_fu_113_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_117_ce = 1'b1;
    end else begin
        grp_fu_117_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_121_ce = 1'b1;
    end else begin
        grp_fu_121_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_125_ce = 1'b1;
    end else begin
        grp_fu_125_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_129_ce = 1'b1;
    end else begin
        grp_fu_129_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_133_ce = 1'b1;
    end else begin
        grp_fu_133_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_137_ce = 1'b1;
    end else begin
        grp_fu_137_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_141_ce = 1'b1;
    end else begin
        grp_fu_141_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_145_ce = 1'b1;
    end else begin
        grp_fu_145_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_150_ce = 1'b1;
    end else begin
        grp_fu_150_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_67_ce = 1'b1;
    end else begin
        grp_fu_67_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_72_ce = 1'b1;
    end else begin
        grp_fu_72_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_76_ce = 1'b1;
    end else begin
        grp_fu_76_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_80_ce = 1'b1;
    end else begin
        grp_fu_80_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_84_ce = 1'b1;
    end else begin
        grp_fu_84_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_88_ce = 1'b1;
    end else begin
        grp_fu_88_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_92_ce = 1'b1;
    end else begin
        grp_fu_92_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_fu_97_ce = 1'b1;
    end else begin
        grp_fu_97_ce = 1'b0;
    end
end

assign and_ln179_1_fu_417_p2 = (and_ln179_7_fu_411_p2 & and_ln179_2_fu_385_p2);

assign and_ln179_2_fu_385_p2 = (grp_fu_109_p2 & and_ln179_fu_381_p2);

assign and_ln179_3_fu_391_p2 = (or_ln179_reg_653 & or_ln179_2_reg_667);

assign and_ln179_4_fu_395_p2 = (grp_fu_113_p2 & and_ln179_3_fu_391_p2);

assign and_ln179_5_fu_401_p2 = (or_ln179_reg_653 & or_ln179_3_reg_674);

assign and_ln179_6_fu_405_p2 = (grp_fu_117_p2 & and_ln179_5_fu_401_p2);

assign and_ln179_7_fu_411_p2 = (and_ln179_6_fu_405_p2 & and_ln179_4_fu_395_p2);

assign and_ln179_fu_381_p2 = (or_ln179_reg_653 & or_ln179_1_reg_660);

assign and_ln184_1_fu_429_p2 = (or_ln179_2_reg_667 & or_ln179_1_reg_660);

assign and_ln184_2_fu_433_p2 = (grp_fu_125_p2 & and_ln184_1_fu_429_p2);

assign and_ln184_3_fu_439_p2 = (or_ln179_3_reg_674 & or_ln179_1_reg_660);

assign and_ln184_4_fu_443_p2 = (grp_fu_129_p2 & and_ln184_3_fu_439_p2);

assign and_ln184_5_fu_489_p2 = (and_ln184_4_fu_443_p2 & and_ln184_2_fu_433_p2);

assign and_ln184_6_fu_495_p2 = (xor_ln179_fu_483_p2 & and_ln184_fu_423_p2);

assign and_ln184_7_fu_501_p2 = (and_ln184_6_fu_495_p2 & and_ln184_5_fu_489_p2);

assign and_ln184_fu_423_p2 = (grp_fu_121_p2 & and_ln179_fu_381_p2);

assign and_ln189_1_fu_477_p2 = (and_ln189_fu_449_p2 & and_ln189_5_fu_471_p2);

assign and_ln189_2_fu_455_p2 = (grp_fu_137_p2 & and_ln184_1_fu_429_p2);

assign and_ln189_3_fu_461_p2 = (or_ln179_3_reg_674 & or_ln179_2_reg_667);

assign and_ln189_4_fu_465_p2 = (grp_fu_141_p2 & and_ln189_3_fu_461_p2);

assign and_ln189_5_fu_471_p2 = (and_ln189_4_fu_465_p2 & and_ln189_2_fu_455_p2);

assign and_ln189_fu_449_p2 = (grp_fu_133_p2 & and_ln179_3_fu_391_p2);

assign and_ln201_fu_599_p2 = (or_ln201_fu_593_p2 & grp_fu_145_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage0_iter45 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage0_iter46 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage0_iter47 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage0_iter48 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_phi_reg_pp0_iter0_p_0_reg_56 = 'bx;

assign ap_return = ap_phi_mux_p_0_phi_fu_60_p4;

assign bitcast_ln201_fu_564_p1 = largest_3_reg_718;

assign d1_3_fu_522_p3 = ((and_ln184_7_reg_695[0:0] === 1'b1) ? d1_4_reg_605_pp0_iter1_reg : d1_fu_517_p3);

assign d1_4_fu_175_p1 = p_Result_s_fu_167_p3;

assign d1_fu_517_p3 = ((and_ln179_1_reg_681[0:0] === 1'b1) ? d2_4_reg_617_pp0_iter1_reg : d1_4_reg_605_pp0_iter1_reg);

assign d2_3_fu_533_p3 = ((and_ln184_7_reg_695[0:0] === 1'b1) ? largest_4_reg_629_pp0_iter1_reg : d2_fu_528_p3);

assign d2_4_fu_204_p1 = p_Result_48_fu_196_p3;

assign d2_fu_528_p3 = ((and_ln179_1_reg_681[0:0] === 1'b1) ? largest_4_reg_629_pp0_iter1_reg : d2_4_reg_617_pp0_iter1_reg);

assign d3_1_fu_507_p3 = ((and_ln189_1_reg_689[0:0] === 1'b1) ? d3_reg_642_pp0_iter1_reg : largest_4_reg_629_pp0_iter1_reg);

assign d3_2_fu_539_p3 = ((and_ln179_1_reg_681[0:0] === 1'b1) ? d3_reg_642_pp0_iter1_reg : d3_1_fu_507_p3);

assign d3_3_fu_545_p3 = ((and_ln184_7_reg_695[0:0] === 1'b1) ? d3_reg_642_pp0_iter1_reg : d3_2_fu_539_p3);

assign d3_fu_262_p1 = p_Result_50_fu_254_p3;

assign grp_fu_145_p0 = ((and_ln184_7_reg_695[0:0] === 1'b1) ? d2_4_reg_617_pp0_iter1_reg : largest_2_fu_551_p3);

assign icmp_ln179_1_fu_295_p2 = ((trunc_ln189_fu_163_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_2_fu_307_p2 = ((tmp_2_fu_279_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln179_3_fu_313_p2 = ((trunc_ln189_1_fu_192_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_4_fu_335_p2 = ((tmp_4_fu_325_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln179_5_fu_341_p2 = ((trunc_ln189_2_fu_221_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_6_fu_363_p2 = ((tmp_6_fu_353_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln179_7_fu_369_p2 = ((trunc_ln189_3_fu_250_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln179_fu_289_p2 = ((tmp_1_fu_269_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln201_1_fu_587_p2 = ((trunc_ln201_fu_577_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln201_fu_581_p2 = ((tmp_14_fu_567_p4 != 8'd255) ? 1'b1 : 1'b0);

assign largest_1_fu_512_p3 = ((and_ln189_1_reg_689[0:0] === 1'b1) ? largest_4_reg_629_pp0_iter1_reg : d3_reg_642_pp0_iter1_reg);

assign largest_2_fu_551_p3 = ((and_ln179_1_reg_681[0:0] === 1'b1) ? d1_4_reg_605_pp0_iter1_reg : largest_1_fu_512_p3);

assign largest_3_fu_557_p3 = ((and_ln184_7_reg_695[0:0] === 1'b1) ? d2_4_reg_617_pp0_iter1_reg : largest_2_fu_551_p3);

assign largest_4_fu_233_p1 = p_Result_49_fu_225_p3;

assign or_ln179_1_fu_319_p2 = (icmp_ln179_3_fu_313_p2 | icmp_ln179_2_fu_307_p2);

assign or_ln179_2_fu_347_p2 = (icmp_ln179_5_fu_341_p2 | icmp_ln179_4_fu_335_p2);

assign or_ln179_3_fu_375_p2 = (icmp_ln179_7_fu_369_p2 | icmp_ln179_6_fu_363_p2);

assign or_ln179_fu_301_p2 = (icmp_ln179_fu_289_p2 | icmp_ln179_1_fu_295_p2);

assign or_ln201_fu_593_p2 = (icmp_ln201_fu_581_p2 | icmp_ln201_1_fu_587_p2);

assign p_Result_48_fu_196_p3 = {{1'd0}, {trunc_ln368_1_fu_188_p1}};

assign p_Result_49_fu_225_p3 = {{1'd0}, {trunc_ln368_2_fu_217_p1}};

assign p_Result_50_fu_254_p3 = {{1'd0}, {trunc_ln368_3_fu_246_p1}};

assign p_Result_s_fu_167_p3 = {{1'd0}, {trunc_ln368_fu_159_p1}};

assign p_Val2_64_fu_184_p1 = a_M_imag_int_reg;

assign p_Val2_65_fu_213_p1 = b_M_real_int_reg;

assign p_Val2_66_fu_242_p1 = b_M_imag_int_reg;

assign p_Val2_s_fu_155_p1 = a_M_real_int_reg;

assign tmp_14_fu_567_p4 = {{bitcast_ln201_fu_564_p1[30:23]}};

assign tmp_1_fu_269_p4 = {{p_Val2_s_fu_155_p1[30:23]}};

assign tmp_2_fu_279_p4 = {{p_Val2_64_fu_184_p1[30:23]}};

assign tmp_4_fu_325_p4 = {{p_Val2_65_fu_213_p1[30:23]}};

assign tmp_6_fu_353_p4 = {{p_Val2_66_fu_242_p1[30:23]}};

assign trunc_ln189_1_fu_192_p1 = p_Val2_64_fu_184_p1[22:0];

assign trunc_ln189_2_fu_221_p1 = p_Val2_65_fu_213_p1[22:0];

assign trunc_ln189_3_fu_250_p1 = p_Val2_66_fu_242_p1[22:0];

assign trunc_ln189_fu_163_p1 = p_Val2_s_fu_155_p1[22:0];

assign trunc_ln201_fu_577_p1 = bitcast_ln201_fu_564_p1[22:0];

assign trunc_ln368_1_fu_188_p1 = p_Val2_64_fu_184_p1[30:0];

assign trunc_ln368_2_fu_217_p1 = p_Val2_65_fu_213_p1[30:0];

assign trunc_ln368_3_fu_246_p1 = p_Val2_66_fu_242_p1[30:0];

assign trunc_ln368_fu_159_p1 = p_Val2_s_fu_155_p1[30:0];

assign xor_ln179_fu_483_p2 = (1'd1 ^ and_ln179_1_fu_417_p2);

always @ (posedge ap_clk) begin
    d1_4_reg_605[31] <= 1'b0;
    d1_4_reg_605_pp0_iter1_reg[31] <= 1'b0;
    d2_4_reg_617[31] <= 1'b0;
    d2_4_reg_617_pp0_iter1_reg[31] <= 1'b0;
    largest_4_reg_629[31] <= 1'b0;
    largest_4_reg_629_pp0_iter1_reg[31] <= 1'b0;
    d3_reg_642[31] <= 1'b0;
    d3_reg_642_pp0_iter1_reg[31] <= 1'b0;
    d1_3_reg_703[31] <= 1'b0;
    d2_3_reg_708[31] <= 1'b0;
    d3_3_reg_713[31] <= 1'b0;
    largest_3_reg_718[31] <= 1'b0;
    largest_3_reg_718_pp0_iter3_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter4_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter5_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter6_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter7_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter8_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter9_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter10_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter11_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter12_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter13_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter14_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter15_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter16_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter17_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter18_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter19_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter20_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter21_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter22_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter23_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter24_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter25_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter26_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter27_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter28_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter29_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter30_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter31_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter32_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter33_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter34_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter35_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter36_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter37_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter38_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter39_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter40_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter41_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter42_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter43_reg[31] <= 1'b0;
    largest_3_reg_718_pp0_iter44_reg[31] <= 1'b0;
end

endmodule //qrf_magnitude_float_s
