// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sin_or_cos_double_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        t_in,
        do_cos,
        ap_return
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] t_in;
input   do_cos;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] ref_4oPi_table_256_V_address0;
reg    ref_4oPi_table_256_V_ce0;
wire   [255:0] ref_4oPi_table_256_V_q0;
wire   [7:0] fourth_order_double_4_address0;
reg    fourth_order_double_4_ce0;
wire   [58:0] fourth_order_double_4_q0;
wire   [7:0] fourth_order_double_5_address0;
reg    fourth_order_double_5_ce0;
wire   [51:0] fourth_order_double_5_q0;
wire   [7:0] fourth_order_double_6_address0;
reg    fourth_order_double_6_ce0;
wire   [43:0] fourth_order_double_6_q0;
wire   [7:0] fourth_order_double_7_address0;
reg    fourth_order_double_7_ce0;
wire   [32:0] fourth_order_double_7_q0;
wire   [7:0] fourth_order_double_s_address0;
reg    fourth_order_double_s_ce0;
wire   [24:0] fourth_order_double_s_q0;
reg   [0:0] p_Result_s_reg_1097;
wire   [10:0] tmp_V_fu_286_p4;
reg   [10:0] tmp_V_reg_1103;
wire   [51:0] tmp_V_4_fu_296_p1;
reg   [51:0] tmp_V_4_reg_1110;
wire   [0:0] closepath_fu_300_p2;
reg   [0:0] closepath_reg_1116;
wire   [6:0] trunc_ln601_fu_335_p1;
reg   [6:0] trunc_ln601_reg_1127;
reg   [169:0] ret_V_20_reg_1132;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln833_3_fu_378_p2;
reg   [0:0] icmp_ln833_3_reg_1147;
reg   [123:0] p_Val2_57_reg_1153;
wire    ap_CS_fsm_state7;
reg   [2:0] trunc_ln_i_reg_1159;
wire   [2:0] p_Val2_58_fu_403_p3;
reg   [2:0] p_Val2_58_reg_1164;
wire    ap_CS_fsm_state8;
wire   [123:0] p_Val2_33_fu_418_p3;
reg   [123:0] p_Val2_33_reg_1170;
reg   [60:0] p_Result_i_i_60_reg_1175;
wire   [5:0] Mx_zeros_V_fu_468_p1;
reg   [5:0] Mx_zeros_V_reg_1180;
wire    ap_CS_fsm_state9;
reg   [62:0] Mx_V_reg_1186;
wire    ap_CS_fsm_state10;
wire  signed [10:0] Ex_V_fu_505_p2;
reg  signed [10:0] Ex_V_reg_1193;
reg   [0:0] isNeg_reg_1199;
wire   [0:0] icmp_ln833_fu_519_p2;
reg   [0:0] icmp_ln833_reg_1205;
wire   [0:0] icmp_ln833_4_fu_524_p2;
reg   [0:0] icmp_ln833_4_reg_1211;
reg   [6:0] p_Result_i_reg_1219;
wire    ap_CS_fsm_state11;
wire   [55:0] B_V_fu_580_p1;
reg   [55:0] B_V_reg_1224;
reg   [48:0] B_trunc_V_reg_1229;
wire    ap_CS_fsm_state12;
wire   [0:0] tmp_fu_594_p10;
reg   [0:0] tmp_reg_1240;
wire   [97:0] r_V_19_fu_615_p1;
reg   [97:0] r_V_19_reg_1246;
wire   [0:0] xor_ln29_fu_624_p2;
reg   [0:0] xor_ln29_reg_1253;
wire   [63:0] zext_ln498_fu_643_p1;
reg   [63:0] zext_ln498_reg_1258;
reg   [48:0] B_squared_V_reg_1275;
wire    ap_CS_fsm_state13;
reg  signed [51:0] fourth_order_double_10_reg_1281;
reg  signed [43:0] fourth_order_double_12_reg_1286;
wire   [97:0] r_V_22_fu_659_p1;
wire    ap_CS_fsm_state14;
reg   [41:0] B_third_power_V_reg_1333;
wire    ap_CS_fsm_state15;
reg   [34:0] B_fourth_power_V_reg_1338;
reg   [58:0] p_Val2_42_reg_1343;
reg   [55:0] trunc_ln5_reg_1348;
reg   [47:0] trunc_ln662_4_reg_1353;
reg   [32:0] fourth_order_double_14_reg_1358;
reg   [24:0] fourth_order_double_16_reg_1363;
wire    ap_CS_fsm_state16;
reg   [28:0] tmp_3_reg_1378;
wire   [63:0] ret_V_23_fu_794_p2;
reg   [63:0] ret_V_23_reg_1383;
reg   [36:0] tmp_2_reg_1388;
wire    ap_CS_fsm_state17;
wire   [0:0] cos_basis_fu_815_p3;
reg   [0:0] cos_basis_reg_1393;
wire    ap_CS_fsm_state18;
wire   [63:0] ret_V_17_fu_832_p2;
reg  signed [63:0] ret_V_17_reg_1400;
wire    ap_CS_fsm_state19;
reg   [62:0] result_V_reg_1415;
wire    ap_CS_fsm_state23;
wire   [11:0] ret_V_fu_878_p2;
reg   [11:0] ret_V_reg_1420;
wire   [0:0] and_ln300_fu_1000_p2;
reg   [0:0] and_ln300_reg_1425;
wire    ap_CS_fsm_state24;
wire    grp_scaled_fixed2ieee_fu_268_ap_ready;
wire    grp_scaled_fixed2ieee_fu_268_ap_done;
wire   [0:0] select_ln311_fu_1021_p3;
reg   [0:0] select_ln311_reg_1430;
wire   [10:0] ret_V_18_fu_1036_p3;
reg   [10:0] ret_V_18_reg_1435;
wire   [51:0] ret_V_19_fu_1067_p3;
reg   [51:0] ret_V_19_reg_1440;
wire    grp_scaled_fixed2ieee_fu_268_ap_start;
wire    grp_scaled_fixed2ieee_fu_268_ap_idle;
wire   [63:0] grp_scaled_fixed2ieee_fu_268_ap_return;
reg    grp_scaled_fixed2ieee_fu_268_ap_start_reg;
wire   [63:0] zext_ln635_fu_330_p1;
wire   [63:0] p_Val2_s_fu_274_p1;
wire   [10:0] add_ln114_2_fu_306_p2;
wire   [10:0] addr_V_fu_312_p3;
wire   [3:0] p_Result_i_i_fu_320_p4;
wire   [255:0] zext_ln744_fu_339_p1;
wire   [255:0] r_V_31_fu_342_p2;
wire   [52:0] p_Result_36_fu_358_p3;
wire   [169:0] grp_fu_372_p0;
wire   [52:0] grp_fu_372_p1;
wire   [222:0] grp_fu_372_p2;
wire   [0:0] trunc_ln745_fu_409_p1;
wire   [123:0] Mx_bits_V_2_fu_413_p2;
wire   [61:0] p_Result_37_fu_435_p3;
reg   [61:0] p_Result_29_fu_442_p4;
wire   [63:0] p_Result_38_fu_452_p3;
reg   [63:0] tmp_i_i_fu_460_p3;
wire   [10:0] add_ln114_fu_472_p2;
wire   [123:0] zext_ln1253_fu_484_p1;
wire   [123:0] r_V_32_fu_487_p2;
wire   [10:0] select_ln482_fu_477_p3;
wire   [10:0] zext_ln655_fu_502_p1;
wire  signed [11:0] sext_ln1334_fu_529_p1;
wire   [11:0] sub_ln1311_fu_532_p2;
wire   [11:0] ush_fu_538_p3;
wire  signed [31:0] sext_ln1311_fu_545_p1;
wire   [62:0] zext_ln1287_fu_549_p1;
wire   [62:0] r_V_fu_553_p2;
wire   [62:0] r_V_17_fu_558_p2;
wire   [62:0] r_V_33_fu_563_p3;
wire   [48:0] grp_fu_618_p0;
wire   [48:0] grp_fu_618_p1;
wire   [0:0] xor_ln29_fu_624_p0;
wire   [0:0] sin_basis_fu_630_p2;
wire   [7:0] p_Result_39_fu_636_p3;
wire   [97:0] grp_fu_618_p2;
wire   [48:0] grp_fu_662_p0;
wire   [48:0] grp_fu_662_p1;
wire   [48:0] grp_fu_667_p0;
wire   [48:0] grp_fu_667_p1;
wire   [55:0] grp_fu_679_p0;
wire   [48:0] grp_fu_691_p0;
wire   [97:0] grp_fu_662_p2;
wire   [97:0] grp_fu_667_p2;
wire   [107:0] grp_fu_679_p2;
wire   [92:0] grp_fu_691_p2;
wire   [41:0] grp_fu_750_p0;
wire   [32:0] grp_fu_750_p1;
wire   [34:0] r_V_40_fu_762_p0;
wire   [24:0] r_V_40_fu_762_p1;
wire   [59:0] r_V_40_fu_762_p2;
wire   [62:0] t1_V_fu_737_p3;
wire  signed [63:0] lhs_V_2_fu_778_p1;
wire  signed [63:0] rhs_V_4_fu_782_p1;
wire   [63:0] ret_V_22_fu_785_p2;
wire  signed [63:0] sext_ln657_fu_791_p1;
wire   [74:0] grp_fu_750_p2;
wire   [0:0] cos_basis_fu_815_p0;
wire   [0:0] xor_ln271_fu_810_p2;
wire   [63:0] zext_ln657_fu_821_p1;
wire   [63:0] ret_V_24_fu_824_p2;
wire   [63:0] zext_ln657_1_fu_829_p1;
wire   [62:0] select_ln272_2_fu_838_p3;
wire   [62:0] grp_fu_851_p1;
wire   [125:0] grp_fu_851_p2;
wire   [10:0] select_ln272_fu_857_p3;
wire  signed [11:0] rhs_V_fu_874_p1;
wire   [63:0] p_Val2_53_fu_885_p1;
wire   [3:0] p_Result_41_fu_911_p3;
wire   [0:0] tmp_s_fu_917_p18;
wire   [0:0] tmp_4_fu_955_p18;
wire   [0:0] select_ln307_fu_1004_p0;
wire   [0:0] select_ln271_fu_993_p3;
wire   [0:0] or_ln311_fu_1016_p2;
wire   [0:0] xor_ln311_fu_1011_p2;
wire   [0:0] p_Result_40_fu_889_p3;
wire   [10:0] tmp_V_5_fu_897_p4;
wire   [10:0] select_ln307_fu_1004_p3;
wire   [10:0] select_ln311_2_fu_1029_p3;
wire   [0:0] and_ln300_2_fu_1044_p2;
wire   [0:0] xor_ln300_fu_1048_p2;
wire   [0:0] or_ln300_fu_1062_p2;
wire   [51:0] select_ln300_5_fu_1054_p3;
wire   [51:0] tmp_V_6_fu_907_p1;
wire    ap_CS_fsm_state25;
wire   [0:0] and_ln307_fu_1075_p2;
wire   [0:0] p_Repl2_6_fu_1079_p3;
wire   [63:0] p_Result_42_fu_1085_p4;
reg   [24:0] ap_NS_fsm;
wire   [222:0] grp_fu_372_p00;
wire   [222:0] grp_fu_372_p10;
wire   [107:0] grp_fu_679_p00;
wire   [92:0] grp_fu_691_p00;
wire   [74:0] grp_fu_750_p00;
wire   [74:0] grp_fu_750_p10;
wire   [125:0] grp_fu_851_p10;
wire   [59:0] r_V_40_fu_762_p00;
wire   [59:0] r_V_40_fu_762_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'd1;
#0 grp_scaled_fixed2ieee_fu_268_ap_start_reg = 1'b0;
end

sin_or_cos_doubleEe0 #(
    .DataWidth( 256 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
ref_4oPi_table_256_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_256_V_address0),
    .ce0(ref_4oPi_table_256_V_ce0),
    .q0(ref_4oPi_table_256_V_q0)
);

sin_or_cos_doubleFfa #(
    .DataWidth( 59 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_4_address0),
    .ce0(fourth_order_double_4_ce0),
    .q0(fourth_order_double_4_q0)
);

sin_or_cos_doubleGfk #(
    .DataWidth( 52 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_5_address0),
    .ce0(fourth_order_double_5_ce0),
    .q0(fourth_order_double_5_q0)
);

sin_or_cos_doubleHfu #(
    .DataWidth( 44 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_6_address0),
    .ce0(fourth_order_double_6_ce0),
    .q0(fourth_order_double_6_q0)
);

sin_or_cos_doubleIfE #(
    .DataWidth( 33 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_7_address0),
    .ce0(fourth_order_double_7_ce0),
    .q0(fourth_order_double_7_q0)
);

sin_or_cos_doubleJfO #(
    .DataWidth( 25 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
fourth_order_double_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fourth_order_double_s_address0),
    .ce0(fourth_order_double_s_ce0),
    .q0(fourth_order_double_s_q0)
);

scaled_fixed2ieee grp_scaled_fixed2ieee_fu_268(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_scaled_fixed2ieee_fu_268_ap_start),
    .ap_done(grp_scaled_fixed2ieee_fu_268_ap_done),
    .ap_idle(grp_scaled_fixed2ieee_fu_268_ap_idle),
    .ap_ready(grp_scaled_fixed2ieee_fu_268_ap_ready),
    .in_V(result_V_reg_1415),
    .prescale(ret_V_reg_1420),
    .ap_return(grp_scaled_fixed2ieee_fu_268_ap_return)
);

music_mul_170ns_5KfY #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 170 ),
    .din1_WIDTH( 53 ),
    .dout_WIDTH( 223 ))
music_mul_170ns_5KfY_U201(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_372_p0),
    .din1(grp_fu_372_p1),
    .ce(1'b1),
    .dout(grp_fu_372_p2)
);

music_mux_83_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
music_mux_83_1_1_1_U202(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(p_Val2_58_reg_1164),
    .dout(tmp_fu_594_p10)
);

music_mul_49ns_49Lf8 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
music_mul_49ns_49Lf8_U203(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_618_p0),
    .din1(grp_fu_618_p1),
    .ce(1'b1),
    .dout(grp_fu_618_p2)
);

music_mul_49ns_49Lf8 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
music_mul_49ns_49Lf8_U204(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_662_p0),
    .din1(grp_fu_662_p1),
    .ce(1'b1),
    .dout(grp_fu_662_p2)
);

music_mul_49ns_49Lf8 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 98 ))
music_mul_49ns_49Lf8_U205(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_667_p0),
    .din1(grp_fu_667_p1),
    .ce(1'b1),
    .dout(grp_fu_667_p2)
);

music_mul_56ns_52Mgi #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 56 ),
    .din1_WIDTH( 52 ),
    .dout_WIDTH( 108 ))
music_mul_56ns_52Mgi_U206(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_679_p0),
    .din1(fourth_order_double_10_reg_1281),
    .ce(1'b1),
    .dout(grp_fu_679_p2)
);

music_mul_49ns_44Ngs #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 44 ),
    .dout_WIDTH( 93 ))
music_mul_49ns_44Ngs_U207(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_691_p0),
    .din1(fourth_order_double_12_reg_1286),
    .ce(1'b1),
    .dout(grp_fu_691_p2)
);

music_mul_42ns_33OgC #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 42 ),
    .din1_WIDTH( 33 ),
    .dout_WIDTH( 75 ))
music_mul_42ns_33OgC_U208(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_750_p0),
    .din1(grp_fu_750_p1),
    .ce(1'b1),
    .dout(grp_fu_750_p2)
);

music_mul_64s_63nPgM #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 63 ),
    .dout_WIDTH( 126 ))
music_mul_64s_63nPgM_U209(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_17_reg_1400),
    .din1(grp_fu_851_p1),
    .ce(1'b1),
    .dout(grp_fu_851_p2)
);

music_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
music_mux_164_1_1_1_U210(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_41_fu_911_p3),
    .dout(tmp_s_fu_917_p18)
);

music_mux_164_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
music_mux_164_1_1_1_U211(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .din16(p_Result_41_fu_911_p3),
    .dout(tmp_4_fu_955_p18)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_scaled_fixed2ieee_fu_268_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state23)) begin
            grp_scaled_fixed2ieee_fu_268_ap_start_reg <= 1'b1;
        end else if ((grp_scaled_fixed2ieee_fu_268_ap_ready == 1'b1)) begin
            grp_scaled_fixed2ieee_fu_268_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        B_V_reg_1224 <= B_V_fu_580_p1;
        B_trunc_V_reg_1229 <= {{r_V_33_fu_563_p3[55:7]}};
        p_Result_i_reg_1219 <= {{r_V_33_fu_563_p3[62:56]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        B_fourth_power_V_reg_1338 <= {{grp_fu_667_p2[97:63]}};
        B_third_power_V_reg_1333 <= {{grp_fu_662_p2[97:56]}};
        fourth_order_double_14_reg_1358 <= fourth_order_double_7_q0;
        fourth_order_double_16_reg_1363 <= fourth_order_double_s_q0;
        p_Val2_42_reg_1343 <= fourth_order_double_4_q0;
        trunc_ln5_reg_1348 <= {{grp_fu_679_p2[107:52]}};
        trunc_ln662_4_reg_1353 <= {{grp_fu_691_p2[92:45]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        B_squared_V_reg_1275 <= {{grp_fu_618_p2[97:49]}};
        fourth_order_double_10_reg_1281 <= fourth_order_double_5_q0;
        fourth_order_double_12_reg_1286 <= fourth_order_double_6_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        Ex_V_reg_1193 <= Ex_V_fu_505_p2;
        Mx_V_reg_1186 <= {{r_V_32_fu_487_p2[123:61]}};
        icmp_ln833_4_reg_1211 <= icmp_ln833_4_fu_524_p2;
        icmp_ln833_reg_1205 <= icmp_ln833_fu_519_p2;
        isNeg_reg_1199 <= Ex_V_fu_505_p2[32'd10];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        Mx_zeros_V_reg_1180 <= Mx_zeros_V_fu_468_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_scaled_fixed2ieee_fu_268_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        and_ln300_reg_1425 <= and_ln300_fu_1000_p2;
        ret_V_18_reg_1435 <= ret_V_18_fu_1036_p3;
        ret_V_19_reg_1440 <= ret_V_19_fu_1067_p3;
        select_ln311_reg_1430 <= select_ln311_fu_1021_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        closepath_reg_1116 <= closepath_fu_300_p2;
        p_Result_s_reg_1097 <= p_Val2_s_fu_274_p1[32'd63];
        tmp_V_4_reg_1110 <= tmp_V_4_fu_296_p1;
        tmp_V_reg_1103 <= {{p_Val2_s_fu_274_p1[62:52]}};
        trunc_ln601_reg_1127 <= trunc_ln601_fu_335_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        cos_basis_reg_1393 <= cos_basis_fu_815_p3;
        ret_V_17_reg_1400 <= ret_V_17_fu_832_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        icmp_ln833_3_reg_1147 <= icmp_ln833_3_fu_378_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        p_Result_i_i_60_reg_1175 <= {{p_Val2_33_fu_418_p3[123:63]}};
        p_Val2_33_reg_1170 <= p_Val2_33_fu_418_p3;
        p_Val2_58_reg_1164 <= p_Val2_58_fu_403_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_Val2_57_reg_1153 <= {{grp_fu_372_p2[166:43]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        r_V_19_reg_1246[48 : 0] <= r_V_19_fu_615_p1[48 : 0];
        tmp_reg_1240 <= tmp_fu_594_p10;
        xor_ln29_reg_1253 <= xor_ln29_fu_624_p2;
        zext_ln498_reg_1258[7 : 0] <= zext_ln498_fu_643_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        result_V_reg_1415 <= {{grp_fu_851_p2[125:63]}};
        ret_V_reg_1420 <= ret_V_fu_878_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ret_V_20_reg_1132 <= {{r_V_31_fu_342_p2[255:86]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        ret_V_23_reg_1383 <= ret_V_23_fu_794_p2;
        tmp_3_reg_1378 <= {{r_V_40_fu_762_p2[59:31]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        tmp_2_reg_1388 <= {{grp_fu_750_p2[74:38]}};
    end
end

always @ (posedge ap_clk) begin
    if (((closepath_reg_1116 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        trunc_ln_i_reg_1159 <= {{grp_fu_372_p2[169:167]}};
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        fourth_order_double_4_ce0 = 1'b1;
    end else begin
        fourth_order_double_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        fourth_order_double_5_ce0 = 1'b1;
    end else begin
        fourth_order_double_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        fourth_order_double_6_ce0 = 1'b1;
    end else begin
        fourth_order_double_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        fourth_order_double_7_ce0 = 1'b1;
    end else begin
        fourth_order_double_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        fourth_order_double_s_ce0 = 1'b1;
    end else begin
        fourth_order_double_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ref_4oPi_table_256_V_ce0 = 1'b1;
    end else begin
        ref_4oPi_table_256_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((grp_scaled_fixed2ieee_fu_268_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign B_V_fu_580_p1 = r_V_33_fu_563_p3[55:0];

assign Ex_V_fu_505_p2 = (select_ln482_fu_477_p3 - zext_ln655_fu_502_p1);

assign Mx_bits_V_2_fu_413_p2 = (124'd0 - p_Val2_57_reg_1153);

assign Mx_zeros_V_fu_468_p1 = tmp_i_i_fu_460_p3[5:0];

assign add_ln114_2_fu_306_p2 = ($signed(11'd1101) + $signed(tmp_V_fu_286_p4));

assign add_ln114_fu_472_p2 = ($signed(11'd1027) + $signed(tmp_V_reg_1103));

assign addr_V_fu_312_p3 = ((closepath_fu_300_p2[0:0] === 1'b1) ? 11'd74 : add_ln114_2_fu_306_p2);

assign and_ln300_2_fu_1044_p2 = (icmp_ln833_reg_1205 & icmp_ln833_3_reg_1147);

assign and_ln300_fu_1000_p2 = (icmp_ln833_reg_1205 & icmp_ln833_3_reg_1147);

assign and_ln307_fu_1075_p2 = (xor_ln29_reg_1253 & p_Result_s_reg_1097);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = p_Result_42_fu_1085_p4;

assign closepath_fu_300_p2 = ((tmp_V_fu_286_p4 < 11'd1022) ? 1'b1 : 1'b0);

assign cos_basis_fu_815_p0 = do_cos;

assign cos_basis_fu_815_p3 = ((cos_basis_fu_815_p0[0:0] === 1'b1) ? xor_ln271_fu_810_p2 : tmp_reg_1240);

assign fourth_order_double_4_address0 = zext_ln498_reg_1258;

assign fourth_order_double_5_address0 = zext_ln498_fu_643_p1;

assign fourth_order_double_6_address0 = zext_ln498_fu_643_p1;

assign fourth_order_double_7_address0 = zext_ln498_reg_1258;

assign fourth_order_double_s_address0 = zext_ln498_reg_1258;

assign grp_fu_372_p0 = grp_fu_372_p00;

assign grp_fu_372_p00 = ret_V_20_reg_1132;

assign grp_fu_372_p1 = grp_fu_372_p10;

assign grp_fu_372_p10 = p_Result_36_fu_358_p3;

assign grp_fu_618_p0 = r_V_19_fu_615_p1;

assign grp_fu_618_p1 = r_V_19_fu_615_p1;

assign grp_fu_662_p0 = r_V_19_reg_1246;

assign grp_fu_662_p1 = r_V_22_fu_659_p1;

assign grp_fu_667_p0 = r_V_22_fu_659_p1;

assign grp_fu_667_p1 = r_V_22_fu_659_p1;

assign grp_fu_679_p0 = grp_fu_679_p00;

assign grp_fu_679_p00 = B_V_reg_1224;

assign grp_fu_691_p0 = grp_fu_691_p00;

assign grp_fu_691_p00 = B_squared_V_reg_1275;

assign grp_fu_750_p0 = grp_fu_750_p00;

assign grp_fu_750_p00 = B_third_power_V_reg_1333;

assign grp_fu_750_p1 = grp_fu_750_p10;

assign grp_fu_750_p10 = fourth_order_double_14_reg_1358;

assign grp_fu_851_p1 = grp_fu_851_p10;

assign grp_fu_851_p10 = select_ln272_2_fu_838_p3;

assign grp_scaled_fixed2ieee_fu_268_ap_start = grp_scaled_fixed2ieee_fu_268_ap_start_reg;

assign icmp_ln833_3_fu_378_p2 = ((tmp_V_4_reg_1110 == 52'd0) ? 1'b1 : 1'b0);

assign icmp_ln833_4_fu_524_p2 = ((tmp_V_reg_1103 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln833_fu_519_p2 = ((tmp_V_reg_1103 == 11'd0) ? 1'b1 : 1'b0);

assign lhs_V_2_fu_778_p1 = $signed(t1_V_fu_737_p3);

assign or_ln300_fu_1062_p2 = (icmp_ln833_4_reg_1211 | and_ln300_fu_1000_p2);

assign or_ln311_fu_1016_p2 = (select_ln271_fu_993_p3 | icmp_ln833_4_reg_1211);

assign p_Repl2_6_fu_1079_p3 = ((and_ln300_reg_1425[0:0] === 1'b1) ? and_ln307_fu_1075_p2 : select_ln311_reg_1430);

integer ap_tvar_int_0;

always @ (p_Result_37_fu_435_p3) begin
    for (ap_tvar_int_0 = 62 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 61 - 0) begin
            p_Result_29_fu_442_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_29_fu_442_p4[ap_tvar_int_0] = p_Result_37_fu_435_p3[61 - ap_tvar_int_0];
        end
    end
end

assign p_Result_36_fu_358_p3 = {{1'd1}, {tmp_V_4_reg_1110}};

assign p_Result_37_fu_435_p3 = {{p_Result_i_i_60_reg_1175}, {1'd1}};

assign p_Result_38_fu_452_p3 = {{2'd3}, {p_Result_29_fu_442_p4}};

assign p_Result_39_fu_636_p3 = {{sin_basis_fu_630_p2}, {p_Result_i_reg_1219}};

assign p_Result_40_fu_889_p3 = p_Val2_53_fu_885_p1[32'd63];

assign p_Result_41_fu_911_p3 = {{p_Result_s_reg_1097}, {p_Val2_58_reg_1164}};

assign p_Result_42_fu_1085_p4 = {{{p_Repl2_6_fu_1079_p3}, {ret_V_18_reg_1435}}, {ret_V_19_reg_1440}};

assign p_Result_i_i_fu_320_p4 = {{addr_V_fu_312_p3[10:7]}};

assign p_Val2_33_fu_418_p3 = ((trunc_ln745_fu_409_p1[0:0] === 1'b1) ? Mx_bits_V_2_fu_413_p2 : p_Val2_57_reg_1153);

assign p_Val2_53_fu_885_p1 = grp_scaled_fixed2ieee_fu_268_ap_return;

assign p_Val2_58_fu_403_p3 = ((closepath_reg_1116[0:0] === 1'b1) ? 3'd0 : trunc_ln_i_reg_1159);

assign p_Val2_s_fu_274_p1 = t_in;

assign r_V_17_fu_558_p2 = Mx_V_reg_1186 << zext_ln1287_fu_549_p1;

assign r_V_19_fu_615_p1 = B_trunc_V_reg_1229;

assign r_V_22_fu_659_p1 = B_squared_V_reg_1275;

assign r_V_31_fu_342_p2 = ref_4oPi_table_256_V_q0 << zext_ln744_fu_339_p1;

assign r_V_32_fu_487_p2 = p_Val2_33_reg_1170 << zext_ln1253_fu_484_p1;

assign r_V_33_fu_563_p3 = ((isNeg_reg_1199[0:0] === 1'b1) ? r_V_fu_553_p2 : r_V_17_fu_558_p2);

assign r_V_40_fu_762_p0 = r_V_40_fu_762_p00;

assign r_V_40_fu_762_p00 = B_fourth_power_V_reg_1338;

assign r_V_40_fu_762_p1 = r_V_40_fu_762_p10;

assign r_V_40_fu_762_p10 = fourth_order_double_16_reg_1363;

assign r_V_40_fu_762_p2 = (r_V_40_fu_762_p0 * r_V_40_fu_762_p1);

assign r_V_fu_553_p2 = Mx_V_reg_1186 >> zext_ln1287_fu_549_p1;

assign ref_4oPi_table_256_V_address0 = zext_ln635_fu_330_p1;

assign ret_V_17_fu_832_p2 = (ret_V_24_fu_824_p2 + zext_ln657_1_fu_829_p1);

assign ret_V_18_fu_1036_p3 = ((and_ln300_fu_1000_p2[0:0] === 1'b1) ? select_ln307_fu_1004_p3 : select_ln311_2_fu_1029_p3);

assign ret_V_19_fu_1067_p3 = ((or_ln300_fu_1062_p2[0:0] === 1'b1) ? select_ln300_5_fu_1054_p3 : tmp_V_6_fu_907_p1);

assign ret_V_22_fu_785_p2 = ($signed(lhs_V_2_fu_778_p1) + $signed(rhs_V_4_fu_782_p1));

assign ret_V_23_fu_794_p2 = ($signed(ret_V_22_fu_785_p2) + $signed(sext_ln657_fu_791_p1));

assign ret_V_24_fu_824_p2 = (ret_V_23_reg_1383 + zext_ln657_fu_821_p1);

assign ret_V_fu_878_p2 = ($signed(12'd0) - $signed(rhs_V_fu_874_p1));

assign rhs_V_4_fu_782_p1 = $signed(trunc_ln5_reg_1348);

assign rhs_V_fu_874_p1 = $signed(select_ln272_fu_857_p3);

assign select_ln271_fu_993_p3 = ((cos_basis_reg_1393[0:0] === 1'b1) ? tmp_s_fu_917_p18 : tmp_4_fu_955_p18);

assign select_ln272_2_fu_838_p3 = ((cos_basis_reg_1393[0:0] === 1'b1) ? 63'd9223372036854775807 : Mx_V_reg_1186);

assign select_ln272_fu_857_p3 = ((cos_basis_reg_1393[0:0] === 1'b1) ? 11'd0 : Ex_V_reg_1193);

assign select_ln300_5_fu_1054_p3 = ((xor_ln300_fu_1048_p2[0:0] === 1'b1) ? 52'd4503599627370495 : 52'd0);

assign select_ln307_fu_1004_p0 = do_cos;

assign select_ln307_fu_1004_p3 = ((select_ln307_fu_1004_p0[0:0] === 1'b1) ? 11'd1023 : 11'd0);

assign select_ln311_2_fu_1029_p3 = ((icmp_ln833_4_reg_1211[0:0] === 1'b1) ? 11'd2047 : tmp_V_5_fu_897_p4);

assign select_ln311_fu_1021_p3 = ((or_ln311_fu_1016_p2[0:0] === 1'b1) ? xor_ln311_fu_1011_p2 : p_Result_40_fu_889_p3);

assign select_ln482_fu_477_p3 = ((closepath_reg_1116[0:0] === 1'b1) ? add_ln114_fu_472_p2 : 11'd0);

assign sext_ln1311_fu_545_p1 = $signed(ush_fu_538_p3);

assign sext_ln1334_fu_529_p1 = Ex_V_reg_1193;

assign sext_ln657_fu_791_p1 = $signed(trunc_ln662_4_reg_1353);

assign sin_basis_fu_630_p2 = (xor_ln29_fu_624_p2 ^ tmp_fu_594_p10);

assign sub_ln1311_fu_532_p2 = ($signed(12'd0) - $signed(sext_ln1334_fu_529_p1));

assign t1_V_fu_737_p3 = {{p_Val2_42_reg_1343}, {4'd0}};

assign tmp_V_4_fu_296_p1 = p_Val2_s_fu_274_p1[51:0];

assign tmp_V_5_fu_897_p4 = {{p_Val2_53_fu_885_p1[62:52]}};

assign tmp_V_6_fu_907_p1 = p_Val2_53_fu_885_p1[51:0];

assign tmp_V_fu_286_p4 = {{p_Val2_s_fu_274_p1[62:52]}};


always @ (p_Result_38_fu_452_p3) begin
    if (p_Result_38_fu_452_p3[0] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd0;
    end else if (p_Result_38_fu_452_p3[1] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd1;
    end else if (p_Result_38_fu_452_p3[2] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd2;
    end else if (p_Result_38_fu_452_p3[3] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd3;
    end else if (p_Result_38_fu_452_p3[4] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd4;
    end else if (p_Result_38_fu_452_p3[5] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd5;
    end else if (p_Result_38_fu_452_p3[6] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd6;
    end else if (p_Result_38_fu_452_p3[7] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd7;
    end else if (p_Result_38_fu_452_p3[8] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd8;
    end else if (p_Result_38_fu_452_p3[9] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd9;
    end else if (p_Result_38_fu_452_p3[10] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd10;
    end else if (p_Result_38_fu_452_p3[11] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd11;
    end else if (p_Result_38_fu_452_p3[12] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd12;
    end else if (p_Result_38_fu_452_p3[13] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd13;
    end else if (p_Result_38_fu_452_p3[14] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd14;
    end else if (p_Result_38_fu_452_p3[15] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd15;
    end else if (p_Result_38_fu_452_p3[16] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd16;
    end else if (p_Result_38_fu_452_p3[17] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd17;
    end else if (p_Result_38_fu_452_p3[18] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd18;
    end else if (p_Result_38_fu_452_p3[19] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd19;
    end else if (p_Result_38_fu_452_p3[20] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd20;
    end else if (p_Result_38_fu_452_p3[21] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd21;
    end else if (p_Result_38_fu_452_p3[22] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd22;
    end else if (p_Result_38_fu_452_p3[23] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd23;
    end else if (p_Result_38_fu_452_p3[24] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd24;
    end else if (p_Result_38_fu_452_p3[25] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd25;
    end else if (p_Result_38_fu_452_p3[26] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd26;
    end else if (p_Result_38_fu_452_p3[27] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd27;
    end else if (p_Result_38_fu_452_p3[28] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd28;
    end else if (p_Result_38_fu_452_p3[29] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd29;
    end else if (p_Result_38_fu_452_p3[30] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd30;
    end else if (p_Result_38_fu_452_p3[31] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd31;
    end else if (p_Result_38_fu_452_p3[32] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd32;
    end else if (p_Result_38_fu_452_p3[33] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd33;
    end else if (p_Result_38_fu_452_p3[34] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd34;
    end else if (p_Result_38_fu_452_p3[35] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd35;
    end else if (p_Result_38_fu_452_p3[36] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd36;
    end else if (p_Result_38_fu_452_p3[37] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd37;
    end else if (p_Result_38_fu_452_p3[38] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd38;
    end else if (p_Result_38_fu_452_p3[39] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd39;
    end else if (p_Result_38_fu_452_p3[40] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd40;
    end else if (p_Result_38_fu_452_p3[41] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd41;
    end else if (p_Result_38_fu_452_p3[42] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd42;
    end else if (p_Result_38_fu_452_p3[43] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd43;
    end else if (p_Result_38_fu_452_p3[44] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd44;
    end else if (p_Result_38_fu_452_p3[45] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd45;
    end else if (p_Result_38_fu_452_p3[46] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd46;
    end else if (p_Result_38_fu_452_p3[47] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd47;
    end else if (p_Result_38_fu_452_p3[48] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd48;
    end else if (p_Result_38_fu_452_p3[49] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd49;
    end else if (p_Result_38_fu_452_p3[50] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd50;
    end else if (p_Result_38_fu_452_p3[51] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd51;
    end else if (p_Result_38_fu_452_p3[52] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd52;
    end else if (p_Result_38_fu_452_p3[53] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd53;
    end else if (p_Result_38_fu_452_p3[54] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd54;
    end else if (p_Result_38_fu_452_p3[55] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd55;
    end else if (p_Result_38_fu_452_p3[56] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd56;
    end else if (p_Result_38_fu_452_p3[57] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd57;
    end else if (p_Result_38_fu_452_p3[58] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd58;
    end else if (p_Result_38_fu_452_p3[59] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd59;
    end else if (p_Result_38_fu_452_p3[60] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd60;
    end else if (p_Result_38_fu_452_p3[61] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd61;
    end else if (p_Result_38_fu_452_p3[62] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd62;
    end else if (p_Result_38_fu_452_p3[63] == 1'b1) begin
        tmp_i_i_fu_460_p3 = 64'd63;
    end else begin
        tmp_i_i_fu_460_p3 = 64'd64;
    end
end

assign trunc_ln601_fu_335_p1 = addr_V_fu_312_p3[6:0];

assign trunc_ln745_fu_409_p1 = p_Val2_58_fu_403_p3[0:0];

assign ush_fu_538_p3 = ((isNeg_reg_1199[0:0] === 1'b1) ? sub_ln1311_fu_532_p2 : sext_ln1334_fu_529_p1);

assign xor_ln271_fu_810_p2 = (tmp_reg_1240 ^ 1'd1);

assign xor_ln29_fu_624_p0 = do_cos;

assign xor_ln29_fu_624_p2 = (xor_ln29_fu_624_p0 ^ 1'd1);

assign xor_ln300_fu_1048_p2 = (1'd1 ^ and_ln300_2_fu_1044_p2);

assign xor_ln311_fu_1011_p2 = (icmp_ln833_4_reg_1211 ^ 1'd1);

assign zext_ln1253_fu_484_p1 = Mx_zeros_V_reg_1180;

assign zext_ln1287_fu_549_p1 = $unsigned(sext_ln1311_fu_545_p1);

assign zext_ln498_fu_643_p1 = p_Result_39_fu_636_p3;

assign zext_ln635_fu_330_p1 = p_Result_i_i_fu_320_p4;

assign zext_ln655_fu_502_p1 = Mx_zeros_V_reg_1180;

assign zext_ln657_1_fu_829_p1 = tmp_3_reg_1378;

assign zext_ln657_fu_821_p1 = tmp_2_reg_1388;

assign zext_ln744_fu_339_p1 = trunc_ln601_reg_1127;

always @ (posedge ap_clk) begin
    r_V_19_reg_1246[97:49] <= 49'b0000000000000000000000000000000000000000000000000;
    zext_ln498_reg_1258[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //sin_or_cos_double_s
