-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bit_reverse is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    X_R_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_R_ce0 : OUT STD_LOGIC;
    X_R_we0 : OUT STD_LOGIC;
    X_R_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_R_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    X_R_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_R_ce1 : OUT STD_LOGIC;
    X_R_we1 : OUT STD_LOGIC;
    X_R_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_R_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    X_I_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_I_ce0 : OUT STD_LOGIC;
    X_I_we0 : OUT STD_LOGIC;
    X_I_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_I_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    X_I_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    X_I_ce1 : OUT STD_LOGIC;
    X_I_we1 : OUT STD_LOGIC;
    X_I_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    X_I_q1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of bit_reverse is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln100_fu_129_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln100_fu_133_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln100_reg_213 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_15_fu_143_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_15_reg_221 : STD_LOGIC_VECTOR (10 downto 0);
    signal i_fu_155_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal rev_fu_169_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln102_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln104_fu_187_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln116_fu_191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln116_reg_244 : STD_LOGIC_VECTOR (0 downto 0);
    signal X_R_addr_reg_248 : STD_LOGIC_VECTOR (9 downto 0);
    signal X_R_addr_4_reg_253 : STD_LOGIC_VECTOR (9 downto 0);
    signal X_I_addr_reg_258 : STD_LOGIC_VECTOR (9 downto 0);
    signal X_I_addr_4_reg_263 : STD_LOGIC_VECTOR (9 downto 0);
    signal temp_reg_268 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal temp_1_reg_273 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_assign_reg_86 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal reversed_reg_98 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln114_fu_137_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_i_reg_109 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_0_i_reg_120 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln118_fu_196_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln119_fu_202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln103_fu_161_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln102_fu_165_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_assign_1_fu_177_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_i_reg_109_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln114_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_0_i_reg_109 <= ap_const_lv4_0;
            elsif (((icmp_ln102_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_i_reg_109 <= i_fu_155_p2;
            end if; 
        end if;
    end process;

    input_assign_reg_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                input_assign_reg_86 <= i_15_reg_221;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                input_assign_reg_86 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    p_0_i_reg_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln114_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                p_0_i_reg_120 <= trunc_ln100_fu_129_p1;
            elsif (((icmp_ln102_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                p_0_i_reg_120 <= zext_ln104_fu_187_p1;
            end if; 
        end if;
    end process;

    reversed_reg_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln114_fu_137_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                reversed_reg_98 <= ap_const_lv32_0;
            elsif (((icmp_ln102_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                reversed_reg_98 <= rev_fu_169_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln116_fu_191_p2 = ap_const_lv1_0) and (icmp_ln102_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                X_I_addr_4_reg_263 <= zext_ln119_fu_202_p1(10 - 1 downto 0);
                X_I_addr_reg_258 <= zext_ln118_fu_196_p1(10 - 1 downto 0);
                X_R_addr_4_reg_253 <= zext_ln119_fu_202_p1(10 - 1 downto 0);
                X_R_addr_reg_248 <= zext_ln118_fu_196_p1(10 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_15_reg_221 <= i_15_fu_143_p2;
                    zext_ln100_reg_213(10 downto 0) <= zext_ln100_fu_133_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln102_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                icmp_ln116_reg_244 <= icmp_ln116_fu_191_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                temp_1_reg_273 <= X_I_q0;
                temp_reg_268 <= X_R_q0;
            end if;
        end if;
    end process;
    zext_ln100_reg_213(31 downto 11) <= "000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln102_fu_149_p2, icmp_ln116_fu_191_p2, icmp_ln114_fu_137_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln114_fu_137_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln116_fu_191_p2 = ap_const_lv1_1) and (icmp_ln102_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                elsif (((icmp_ln116_fu_191_p2 = ap_const_lv1_0) and (icmp_ln102_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;

    X_I_address0_assign_proc : process(ap_CS_fsm_state3, X_I_addr_reg_258, ap_CS_fsm_state4, zext_ln118_fu_196_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            X_I_address0 <= X_I_addr_reg_258;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            X_I_address0 <= zext_ln118_fu_196_p1(10 - 1 downto 0);
        else 
            X_I_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_I_address1_assign_proc : process(ap_CS_fsm_state3, X_I_addr_4_reg_263, ap_CS_fsm_state5, zext_ln119_fu_202_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            X_I_address1 <= X_I_addr_4_reg_263;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            X_I_address1 <= zext_ln119_fu_202_p1(10 - 1 downto 0);
        else 
            X_I_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_I_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            X_I_ce0 <= ap_const_logic_1;
        else 
            X_I_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    X_I_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            X_I_ce1 <= ap_const_logic_1;
        else 
            X_I_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    X_I_d0 <= X_I_q1;
    X_I_d1 <= temp_1_reg_273;

    X_I_we0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            X_I_we0 <= ap_const_logic_1;
        else 
            X_I_we0 <= ap_const_logic_0;
        end if; 
    end process;


    X_I_we1_assign_proc : process(icmp_ln116_reg_244, ap_CS_fsm_state5)
    begin
        if (((icmp_ln116_reg_244 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            X_I_we1 <= ap_const_logic_1;
        else 
            X_I_we1 <= ap_const_logic_0;
        end if; 
    end process;


    X_R_address0_assign_proc : process(ap_CS_fsm_state3, X_R_addr_reg_248, ap_CS_fsm_state4, zext_ln118_fu_196_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            X_R_address0 <= X_R_addr_reg_248;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            X_R_address0 <= zext_ln118_fu_196_p1(10 - 1 downto 0);
        else 
            X_R_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_R_address1_assign_proc : process(ap_CS_fsm_state3, X_R_addr_4_reg_253, ap_CS_fsm_state5, zext_ln119_fu_202_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            X_R_address1 <= X_R_addr_4_reg_253;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            X_R_address1 <= zext_ln119_fu_202_p1(10 - 1 downto 0);
        else 
            X_R_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    X_R_ce0_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            X_R_ce0 <= ap_const_logic_1;
        else 
            X_R_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    X_R_ce1_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            X_R_ce1 <= ap_const_logic_1;
        else 
            X_R_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    X_R_d0 <= X_R_q1;
    X_R_d1 <= temp_reg_268;

    X_R_we0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            X_R_we0 <= ap_const_logic_1;
        else 
            X_R_we0 <= ap_const_logic_0;
        end if; 
    end process;


    X_R_we1_assign_proc : process(icmp_ln116_reg_244, ap_CS_fsm_state5)
    begin
        if (((icmp_ln116_reg_244 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            X_R_we1 <= ap_const_logic_1;
        else 
            X_R_we1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln114_fu_137_p2)
    begin
        if ((((icmp_ln114_fu_137_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln114_fu_137_p2)
    begin
        if (((icmp_ln114_fu_137_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_15_fu_143_p2 <= std_logic_vector(unsigned(ap_const_lv11_1) + unsigned(input_assign_reg_86));
    i_fu_155_p2 <= std_logic_vector(unsigned(i_0_i_reg_109) + unsigned(ap_const_lv4_1));
    icmp_ln102_fu_149_p2 <= "1" when (i_0_i_reg_109 = ap_const_lv4_A) else "0";
    icmp_ln114_fu_137_p2 <= "1" when (input_assign_reg_86 = ap_const_lv11_400) else "0";
    icmp_ln116_fu_191_p2 <= "1" when (unsigned(zext_ln100_reg_213) > unsigned(reversed_reg_98)) else "0";
    input_assign_1_fu_177_p4 <= p_0_i_reg_120(9 downto 1);
    rev_fu_169_p3 <= (trunc_ln103_fu_161_p1 & trunc_ln102_fu_165_p1);
    trunc_ln100_fu_129_p1 <= input_assign_reg_86(10 - 1 downto 0);
    trunc_ln102_fu_165_p1 <= p_0_i_reg_120(1 - 1 downto 0);
    trunc_ln103_fu_161_p1 <= reversed_reg_98(31 - 1 downto 0);
    zext_ln100_fu_133_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_assign_reg_86),32));
    zext_ln104_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_assign_1_fu_177_p4),10));
    zext_ln118_fu_196_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_assign_reg_86),64));
    zext_ln119_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(reversed_reg_98),64));
end behav;
