// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Autocorrelation.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Autocorrelation::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Autocorrelation::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<43> Autocorrelation::ap_ST_fsm_state1 = "1";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state2 = "10";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state3 = "100";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state4 = "1000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state5 = "10000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state6 = "100000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state7 = "1000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state8 = "10000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state9 = "100000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state10 = "1000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state11 = "10000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state12 = "100000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<43> Autocorrelation::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<32> Autocorrelation::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> Autocorrelation::ap_const_lv32_8 = "1000";
const sc_lv<32> Autocorrelation::ap_const_lv32_15 = "10101";
const sc_lv<32> Autocorrelation::ap_const_lv32_D = "1101";
const sc_lv<32> Autocorrelation::ap_const_lv32_1A = "11010";
const sc_lv<32> Autocorrelation::ap_const_lv32_1 = "1";
const sc_lv<1> Autocorrelation::ap_const_lv1_0 = "0";
const sc_lv<32> Autocorrelation::ap_const_lv32_2 = "10";
const sc_lv<32> Autocorrelation::ap_const_lv32_3 = "11";
const sc_lv<32> Autocorrelation::ap_const_lv32_4 = "100";
const sc_lv<32> Autocorrelation::ap_const_lv32_5 = "101";
const sc_lv<32> Autocorrelation::ap_const_lv32_12 = "10010";
const sc_lv<3> Autocorrelation::ap_const_lv3_0 = "000";
const sc_lv<1> Autocorrelation::ap_const_lv1_1 = "1";
const sc_lv<32> Autocorrelation::ap_const_lv32_2A = "101010";
const sc_lv<4> Autocorrelation::ap_const_lv4_0 = "0000";
const sc_lv<32> Autocorrelation::ap_const_lv32_9 = "1001";
const sc_lv<32> Autocorrelation::ap_const_lv32_E = "1110";
const sc_lv<32> Autocorrelation::ap_const_lv32_16 = "10110";
const sc_lv<32> Autocorrelation::ap_const_lv32_41200000 = "1000001001000000000000000000000";
const sc_lv<32> Autocorrelation::ap_const_lv32_42C80000 = "1000010110010000000000000000000";
const sc_lv<32> Autocorrelation::ap_const_lv32_1B = "11011";
const sc_lv<3> Autocorrelation::ap_const_lv3_4 = "100";
const sc_lv<3> Autocorrelation::ap_const_lv3_1 = "1";
const sc_lv<2> Autocorrelation::ap_const_lv2_0 = "00";
const sc_lv<4> Autocorrelation::ap_const_lv4_A = "1010";
const sc_lv<4> Autocorrelation::ap_const_lv4_1 = "1";
const sc_lv<32> Autocorrelation::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<2> Autocorrelation::ap_const_lv2_1 = "1";
const bool Autocorrelation::ap_const_boolean_1 = true;

Autocorrelation::Autocorrelation(sc_module_name name) : sc_module(name), mVcdFile(0) {
    music_faddfsub_32ibs_U40 = new music_faddfsub_32ibs<1,5,32,32,32>("music_faddfsub_32ibs_U40");
    music_faddfsub_32ibs_U40->clk(ap_clk);
    music_faddfsub_32ibs_U40->reset(ap_rst);
    music_faddfsub_32ibs_U40->din0(grp_fu_173_p0);
    music_faddfsub_32ibs_U40->din1(grp_fu_173_p1);
    music_faddfsub_32ibs_U40->opcode(grp_fu_173_opcode);
    music_faddfsub_32ibs_U40->ce(ap_var_for_const0);
    music_faddfsub_32ibs_U40->dout(grp_fu_173_p2);
    music_faddfsub_32ibs_U41 = new music_faddfsub_32ibs<1,5,32,32,32>("music_faddfsub_32ibs_U41");
    music_faddfsub_32ibs_U41->clk(ap_clk);
    music_faddfsub_32ibs_U41->reset(ap_rst);
    music_faddfsub_32ibs_U41->din0(grp_fu_177_p0);
    music_faddfsub_32ibs_U41->din1(grp_fu_177_p1);
    music_faddfsub_32ibs_U41->opcode(grp_fu_177_opcode);
    music_faddfsub_32ibs_U41->ce(ap_var_for_const0);
    music_faddfsub_32ibs_U41->dout(grp_fu_177_p2);
    music_fmul_32ns_3jbC_U42 = new music_fmul_32ns_3jbC<1,4,32,32,32>("music_fmul_32ns_3jbC_U42");
    music_fmul_32ns_3jbC_U42->clk(ap_clk);
    music_fmul_32ns_3jbC_U42->reset(ap_rst);
    music_fmul_32ns_3jbC_U42->din0(grp_fu_183_p0);
    music_fmul_32ns_3jbC_U42->din1(grp_fu_183_p1);
    music_fmul_32ns_3jbC_U42->ce(ap_var_for_const0);
    music_fmul_32ns_3jbC_U42->dout(grp_fu_183_p2);
    music_fmul_32ns_3jbC_U43 = new music_fmul_32ns_3jbC<1,4,32,32,32>("music_fmul_32ns_3jbC_U43");
    music_fmul_32ns_3jbC_U43->clk(ap_clk);
    music_fmul_32ns_3jbC_U43->reset(ap_rst);
    music_fmul_32ns_3jbC_U43->din0(grp_fu_189_p0);
    music_fmul_32ns_3jbC_U43->din1(grp_fu_189_p1);
    music_fmul_32ns_3jbC_U43->ce(ap_var_for_const0);
    music_fmul_32ns_3jbC_U43->dout(grp_fu_189_p2);
    music_fmul_32ns_3jbC_U44 = new music_fmul_32ns_3jbC<1,4,32,32,32>("music_fmul_32ns_3jbC_U44");
    music_fmul_32ns_3jbC_U44->clk(ap_clk);
    music_fmul_32ns_3jbC_U44->reset(ap_rst);
    music_fmul_32ns_3jbC_U44->din0(grp_fu_195_p0);
    music_fmul_32ns_3jbC_U44->din1(grp_fu_195_p1);
    music_fmul_32ns_3jbC_U44->ce(ap_var_for_const0);
    music_fmul_32ns_3jbC_U44->dout(grp_fu_195_p2);
    music_fmul_32ns_3jbC_U45 = new music_fmul_32ns_3jbC<1,4,32,32,32>("music_fmul_32ns_3jbC_U45");
    music_fmul_32ns_3jbC_U45->clk(ap_clk);
    music_fmul_32ns_3jbC_U45->reset(ap_rst);
    music_fmul_32ns_3jbC_U45->din0(grp_fu_201_p0);
    music_fmul_32ns_3jbC_U45->din1(grp_fu_201_p1);
    music_fmul_32ns_3jbC_U45->ce(ap_var_for_const0);
    music_fmul_32ns_3jbC_U45->dout(grp_fu_201_p2);
    music_fdiv_32ns_3ncg_U46 = new music_fdiv_32ns_3ncg<1,16,32,32,32>("music_fdiv_32ns_3ncg_U46");
    music_fdiv_32ns_3ncg_U46->clk(ap_clk);
    music_fdiv_32ns_3ncg_U46->reset(ap_rst);
    music_fdiv_32ns_3ncg_U46->din0(reg_239);
    music_fdiv_32ns_3ncg_U46->din1(ap_var_for_const1);
    music_fdiv_32ns_3ncg_U46->ce(ap_var_for_const0);
    music_fdiv_32ns_3ncg_U46->dout(grp_fu_207_p2);
    music_fdiv_32ns_3ncg_U47 = new music_fdiv_32ns_3ncg<1,16,32,32,32>("music_fdiv_32ns_3ncg_U47");
    music_fdiv_32ns_3ncg_U47->clk(ap_clk);
    music_fdiv_32ns_3ncg_U47->reset(ap_rst);
    music_fdiv_32ns_3ncg_U47->din0(reg_245);
    music_fdiv_32ns_3ncg_U47->din1(ap_var_for_const1);
    music_fdiv_32ns_3ncg_U47->ce(ap_var_for_const0);
    music_fdiv_32ns_3ncg_U47->dout(grp_fu_213_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Rx_M_imag_address0);
    sensitive << ( Rx_M_imag_addr_reg_407 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_Rx_M_imag_ce0);
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_Rx_M_imag_d0);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( grp_fu_213_p2 );

    SC_METHOD(thread_Rx_M_imag_we0);
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_Rx_M_real_address0);
    sensitive << ( Rx_M_real_addr11_reg_402 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_Rx_M_real_ce0);
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_Rx_M_real_d0);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( grp_fu_207_p2 );

    SC_METHOD(thread_Rx_M_real_we0);
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_X_M_imag_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln94_2_fu_350_p1 );

    SC_METHOD(thread_X_M_imag_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln94_1_fu_339_p1 );

    SC_METHOD(thread_X_M_imag_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_X_M_imag_ce1);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_X_M_real_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln94_2_fu_350_p1 );

    SC_METHOD(thread_X_M_real_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln94_1_fu_339_p1 );

    SC_METHOD(thread_X_M_real_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_X_M_real_ce1);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_add_ln94_1_fu_345_p2);
    sensitive << ( zext_ln96_1_reg_397 );
    sensitive << ( zext_ln94_fu_330_p1 );

    SC_METHOD(thread_add_ln94_fu_334_p2);
    sensitive << ( zext_ln96_reg_379 );
    sensitive << ( zext_ln94_fu_330_p1 );

    SC_METHOD(thread_add_ln96_fu_299_p2);
    sensitive << ( zext_ln91_reg_384 );
    sensitive << ( zext_ln96_2_fu_295_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln90_fu_251_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln90_fu_251_p2 );

    SC_METHOD(thread_bitcast_ln667_fu_356_p1);
    sensitive << ( X_M_imag_load_reg_446 );

    SC_METHOD(thread_grp_fu_173_opcode);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_grp_fu_173_p0);
    sensitive << ( reg_219 );
    sensitive << ( p_r_M_real_reg_150 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_grp_fu_173_p1);
    sensitive << ( reg_224 );
    sensitive << ( reg_239 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_grp_fu_177_opcode);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_grp_fu_177_p0);
    sensitive << ( reg_229 );
    sensitive << ( p_r_M_imag_reg_138 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_grp_fu_177_p1);
    sensitive << ( reg_234 );
    sensitive << ( reg_245 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_grp_fu_183_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_r_M_real_17_reg_451 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_r_M_real_reg_150 );

    SC_METHOD(thread_grp_fu_183_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_t_real_reg_440 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_189_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_r_M_imag_16_reg_457 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_r_M_imag_reg_138 );

    SC_METHOD(thread_grp_fu_189_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_t_imag_fu_365_p1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_195_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_r_M_imag_16_reg_457 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_r_M_imag_reg_138 );

    SC_METHOD(thread_grp_fu_195_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_t_real_reg_440 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_fu_201_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_r_M_real_17_reg_451 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( p_r_M_real_reg_150 );

    SC_METHOD(thread_grp_fu_201_p1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( p_t_imag_fu_365_p1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_icmp_ln90_fu_251_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( x_0_reg_116 );

    SC_METHOD(thread_icmp_ln91_fu_279_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( y_0_reg_127 );

    SC_METHOD(thread_icmp_ln93_fu_310_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( l_0_reg_162 );

    SC_METHOD(thread_l_fu_316_p2);
    sensitive << ( l_0_reg_162 );

    SC_METHOD(thread_p_t_imag_fu_365_p1);
    sensitive << ( xor_ln667_fu_359_p2 );

    SC_METHOD(thread_tmp_fu_267_p3);
    sensitive << ( x_0_reg_116 );

    SC_METHOD(thread_tmp_s_fu_322_p3);
    sensitive << ( l_0_reg_162 );

    SC_METHOD(thread_x_fu_257_p2);
    sensitive << ( x_0_reg_116 );

    SC_METHOD(thread_xor_ln667_fu_359_p2);
    sensitive << ( bitcast_ln667_fu_356_p1 );

    SC_METHOD(thread_y_fu_285_p2);
    sensitive << ( y_0_reg_127 );

    SC_METHOD(thread_zext_ln91_fu_275_p1);
    sensitive << ( tmp_fu_267_p3 );

    SC_METHOD(thread_zext_ln94_1_fu_339_p1);
    sensitive << ( add_ln94_fu_334_p2 );

    SC_METHOD(thread_zext_ln94_2_fu_350_p1);
    sensitive << ( add_ln94_1_fu_345_p2 );

    SC_METHOD(thread_zext_ln94_fu_330_p1);
    sensitive << ( tmp_s_fu_322_p3 );

    SC_METHOD(thread_zext_ln96_1_fu_291_p1);
    sensitive << ( y_0_reg_127 );

    SC_METHOD(thread_zext_ln96_2_fu_295_p1);
    sensitive << ( y_0_reg_127 );

    SC_METHOD(thread_zext_ln96_3_fu_304_p1);
    sensitive << ( add_ln96_fu_299_p2 );

    SC_METHOD(thread_zext_ln96_fu_263_p1);
    sensitive << ( x_0_reg_116 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln90_fu_251_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln91_fu_279_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln93_fu_310_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Autocorrelation_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, X_M_real_address0, "(port)X_M_real_address0");
    sc_trace(mVcdFile, X_M_real_ce0, "(port)X_M_real_ce0");
    sc_trace(mVcdFile, X_M_real_q0, "(port)X_M_real_q0");
    sc_trace(mVcdFile, X_M_real_address1, "(port)X_M_real_address1");
    sc_trace(mVcdFile, X_M_real_ce1, "(port)X_M_real_ce1");
    sc_trace(mVcdFile, X_M_real_q1, "(port)X_M_real_q1");
    sc_trace(mVcdFile, X_M_imag_address0, "(port)X_M_imag_address0");
    sc_trace(mVcdFile, X_M_imag_ce0, "(port)X_M_imag_ce0");
    sc_trace(mVcdFile, X_M_imag_q0, "(port)X_M_imag_q0");
    sc_trace(mVcdFile, X_M_imag_address1, "(port)X_M_imag_address1");
    sc_trace(mVcdFile, X_M_imag_ce1, "(port)X_M_imag_ce1");
    sc_trace(mVcdFile, X_M_imag_q1, "(port)X_M_imag_q1");
    sc_trace(mVcdFile, Rx_M_real_address0, "(port)Rx_M_real_address0");
    sc_trace(mVcdFile, Rx_M_real_ce0, "(port)Rx_M_real_ce0");
    sc_trace(mVcdFile, Rx_M_real_we0, "(port)Rx_M_real_we0");
    sc_trace(mVcdFile, Rx_M_real_d0, "(port)Rx_M_real_d0");
    sc_trace(mVcdFile, Rx_M_imag_address0, "(port)Rx_M_imag_address0");
    sc_trace(mVcdFile, Rx_M_imag_ce0, "(port)Rx_M_imag_ce0");
    sc_trace(mVcdFile, Rx_M_imag_we0, "(port)Rx_M_imag_we0");
    sc_trace(mVcdFile, Rx_M_imag_d0, "(port)Rx_M_imag_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_183_p2, "grp_fu_183_p2");
    sc_trace(mVcdFile, reg_219, "reg_219");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, grp_fu_189_p2, "grp_fu_189_p2");
    sc_trace(mVcdFile, reg_224, "reg_224");
    sc_trace(mVcdFile, grp_fu_195_p2, "grp_fu_195_p2");
    sc_trace(mVcdFile, reg_229, "reg_229");
    sc_trace(mVcdFile, grp_fu_201_p2, "grp_fu_201_p2");
    sc_trace(mVcdFile, reg_234, "reg_234");
    sc_trace(mVcdFile, grp_fu_173_p2, "grp_fu_173_p2");
    sc_trace(mVcdFile, reg_239, "reg_239");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, grp_fu_177_p2, "grp_fu_177_p2");
    sc_trace(mVcdFile, reg_245, "reg_245");
    sc_trace(mVcdFile, x_fu_257_p2, "x_fu_257_p2");
    sc_trace(mVcdFile, x_reg_374, "x_reg_374");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln96_fu_263_p1, "zext_ln96_fu_263_p1");
    sc_trace(mVcdFile, zext_ln96_reg_379, "zext_ln96_reg_379");
    sc_trace(mVcdFile, icmp_ln90_fu_251_p2, "icmp_ln90_fu_251_p2");
    sc_trace(mVcdFile, zext_ln91_fu_275_p1, "zext_ln91_fu_275_p1");
    sc_trace(mVcdFile, zext_ln91_reg_384, "zext_ln91_reg_384");
    sc_trace(mVcdFile, y_fu_285_p2, "y_fu_285_p2");
    sc_trace(mVcdFile, y_reg_392, "y_reg_392");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln96_1_fu_291_p1, "zext_ln96_1_fu_291_p1");
    sc_trace(mVcdFile, zext_ln96_1_reg_397, "zext_ln96_1_reg_397");
    sc_trace(mVcdFile, icmp_ln91_fu_279_p2, "icmp_ln91_fu_279_p2");
    sc_trace(mVcdFile, Rx_M_real_addr11_reg_402, "Rx_M_real_addr11_reg_402");
    sc_trace(mVcdFile, Rx_M_imag_addr_reg_407, "Rx_M_imag_addr_reg_407");
    sc_trace(mVcdFile, l_fu_316_p2, "l_fu_316_p2");
    sc_trace(mVcdFile, l_reg_415, "l_reg_415");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln93_fu_310_p2, "icmp_ln93_fu_310_p2");
    sc_trace(mVcdFile, p_t_real_reg_440, "p_t_real_reg_440");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, X_M_imag_load_reg_446, "X_M_imag_load_reg_446");
    sc_trace(mVcdFile, p_r_M_real_17_reg_451, "p_r_M_real_17_reg_451");
    sc_trace(mVcdFile, p_r_M_imag_16_reg_457, "p_r_M_imag_16_reg_457");
    sc_trace(mVcdFile, p_t_imag_fu_365_p1, "p_t_imag_fu_365_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, x_0_reg_116, "x_0_reg_116");
    sc_trace(mVcdFile, y_0_reg_127, "y_0_reg_127");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, p_r_M_imag_reg_138, "p_r_M_imag_reg_138");
    sc_trace(mVcdFile, p_r_M_real_reg_150, "p_r_M_real_reg_150");
    sc_trace(mVcdFile, l_0_reg_162, "l_0_reg_162");
    sc_trace(mVcdFile, zext_ln96_3_fu_304_p1, "zext_ln96_3_fu_304_p1");
    sc_trace(mVcdFile, zext_ln94_1_fu_339_p1, "zext_ln94_1_fu_339_p1");
    sc_trace(mVcdFile, zext_ln94_2_fu_350_p1, "zext_ln94_2_fu_350_p1");
    sc_trace(mVcdFile, grp_fu_207_p2, "grp_fu_207_p2");
    sc_trace(mVcdFile, grp_fu_213_p2, "grp_fu_213_p2");
    sc_trace(mVcdFile, grp_fu_173_p0, "grp_fu_173_p0");
    sc_trace(mVcdFile, grp_fu_173_p1, "grp_fu_173_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, grp_fu_177_p0, "grp_fu_177_p0");
    sc_trace(mVcdFile, grp_fu_177_p1, "grp_fu_177_p1");
    sc_trace(mVcdFile, grp_fu_183_p0, "grp_fu_183_p0");
    sc_trace(mVcdFile, grp_fu_183_p1, "grp_fu_183_p1");
    sc_trace(mVcdFile, grp_fu_189_p0, "grp_fu_189_p0");
    sc_trace(mVcdFile, grp_fu_189_p1, "grp_fu_189_p1");
    sc_trace(mVcdFile, grp_fu_195_p0, "grp_fu_195_p0");
    sc_trace(mVcdFile, grp_fu_195_p1, "grp_fu_195_p1");
    sc_trace(mVcdFile, grp_fu_201_p0, "grp_fu_201_p0");
    sc_trace(mVcdFile, grp_fu_201_p1, "grp_fu_201_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, tmp_fu_267_p3, "tmp_fu_267_p3");
    sc_trace(mVcdFile, zext_ln96_2_fu_295_p1, "zext_ln96_2_fu_295_p1");
    sc_trace(mVcdFile, add_ln96_fu_299_p2, "add_ln96_fu_299_p2");
    sc_trace(mVcdFile, tmp_s_fu_322_p3, "tmp_s_fu_322_p3");
    sc_trace(mVcdFile, zext_ln94_fu_330_p1, "zext_ln94_fu_330_p1");
    sc_trace(mVcdFile, add_ln94_fu_334_p2, "add_ln94_fu_334_p2");
    sc_trace(mVcdFile, add_ln94_1_fu_345_p2, "add_ln94_1_fu_345_p2");
    sc_trace(mVcdFile, bitcast_ln667_fu_356_p1, "bitcast_ln667_fu_356_p1");
    sc_trace(mVcdFile, xor_ln667_fu_359_p2, "xor_ln667_fu_359_p2");
    sc_trace(mVcdFile, grp_fu_173_opcode, "grp_fu_173_opcode");
    sc_trace(mVcdFile, grp_fu_177_opcode, "grp_fu_177_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Autocorrelation::~Autocorrelation() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete music_faddfsub_32ibs_U40;
    delete music_faddfsub_32ibs_U41;
    delete music_fmul_32ns_3jbC_U42;
    delete music_fmul_32ns_3jbC_U43;
    delete music_fmul_32ns_3jbC_U44;
    delete music_fmul_32ns_3jbC_U45;
    delete music_fdiv_32ns_3ncg_U46;
    delete music_fdiv_32ns_3ncg_U47;
}

void Autocorrelation::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void Autocorrelation::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_42C80000;
}

void Autocorrelation::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        l_0_reg_162 = l_reg_415.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln91_fu_279_p2.read()))) {
        l_0_reg_162 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        p_r_M_imag_reg_138 = grp_fu_177_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln91_fu_279_p2.read()))) {
        p_r_M_imag_reg_138 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        p_r_M_real_reg_150 = grp_fu_173_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln91_fu_279_p2.read()))) {
        p_r_M_real_reg_150 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln91_fu_279_p2.read(), ap_const_lv1_1))) {
        x_0_reg_116 = x_reg_374.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        x_0_reg_116 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        y_0_reg_127 = y_reg_392.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln90_fu_251_p2.read(), ap_const_lv1_0))) {
        y_0_reg_127 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln91_fu_279_p2.read()))) {
        Rx_M_imag_addr_reg_407 =  (sc_lv<4>) (zext_ln96_3_fu_304_p1.read());
        Rx_M_real_addr11_reg_402 =  (sc_lv<4>) (zext_ln96_3_fu_304_p1.read());
        zext_ln96_1_reg_397 = zext_ln96_1_fu_291_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        X_M_imag_load_reg_446 = X_M_imag_q0.read();
        p_r_M_imag_16_reg_457 = X_M_imag_q1.read();
        p_r_M_real_17_reg_451 = X_M_real_q1.read();
        p_t_real_reg_440 = X_M_real_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        l_reg_415 = l_fu_316_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()))) {
        reg_219 = grp_fu_183_p2.read();
        reg_224 = grp_fu_189_p2.read();
        reg_229 = grp_fu_195_p2.read();
        reg_234 = grp_fu_201_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()))) {
        reg_239 = grp_fu_173_p2.read();
        reg_245 = grp_fu_177_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        x_reg_374 = x_fu_257_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        y_reg_392 = y_fu_285_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln90_fu_251_p2.read(), ap_const_lv1_0))) {
        zext_ln91_reg_384 = zext_ln91_fu_275_p1.read();
        zext_ln96_reg_379 = zext_ln96_fu_263_p1.read();
    }
}

void Autocorrelation::thread_Rx_M_imag_address0() {
    Rx_M_imag_address0 = Rx_M_imag_addr_reg_407.read();
}

void Autocorrelation::thread_Rx_M_imag_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        Rx_M_imag_ce0 = ap_const_logic_1;
    } else {
        Rx_M_imag_ce0 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_Rx_M_imag_d0() {
    Rx_M_imag_d0 = grp_fu_213_p2.read();
}

void Autocorrelation::thread_Rx_M_imag_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        Rx_M_imag_we0 = ap_const_logic_1;
    } else {
        Rx_M_imag_we0 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_Rx_M_real_address0() {
    Rx_M_real_address0 = Rx_M_real_addr11_reg_402.read();
}

void Autocorrelation::thread_Rx_M_real_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        Rx_M_real_ce0 = ap_const_logic_1;
    } else {
        Rx_M_real_ce0 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_Rx_M_real_d0() {
    Rx_M_real_d0 = grp_fu_207_p2.read();
}

void Autocorrelation::thread_Rx_M_real_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        Rx_M_real_we0 = ap_const_logic_1;
    } else {
        Rx_M_real_we0 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_X_M_imag_address0() {
    X_M_imag_address0 =  (sc_lv<6>) (zext_ln94_2_fu_350_p1.read());
}

void Autocorrelation::thread_X_M_imag_address1() {
    X_M_imag_address1 =  (sc_lv<6>) (zext_ln94_1_fu_339_p1.read());
}

void Autocorrelation::thread_X_M_imag_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        X_M_imag_ce0 = ap_const_logic_1;
    } else {
        X_M_imag_ce0 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_X_M_imag_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        X_M_imag_ce1 = ap_const_logic_1;
    } else {
        X_M_imag_ce1 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_X_M_real_address0() {
    X_M_real_address0 =  (sc_lv<6>) (zext_ln94_2_fu_350_p1.read());
}

void Autocorrelation::thread_X_M_real_address1() {
    X_M_real_address1 =  (sc_lv<6>) (zext_ln94_1_fu_339_p1.read());
}

void Autocorrelation::thread_X_M_real_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        X_M_real_ce0 = ap_const_logic_1;
    } else {
        X_M_real_ce0 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_X_M_real_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        X_M_real_ce1 = ap_const_logic_1;
    } else {
        X_M_real_ce1 = ap_const_logic_0;
    }
}

void Autocorrelation::thread_add_ln94_1_fu_345_p2() {
    add_ln94_1_fu_345_p2 = (!zext_ln96_1_reg_397.read().is_01() || !zext_ln94_fu_330_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln96_1_reg_397.read()) + sc_biguint<7>(zext_ln94_fu_330_p1.read()));
}

void Autocorrelation::thread_add_ln94_fu_334_p2() {
    add_ln94_fu_334_p2 = (!zext_ln96_reg_379.read().is_01() || !zext_ln94_fu_330_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln96_reg_379.read()) + sc_biguint<7>(zext_ln94_fu_330_p1.read()));
}

void Autocorrelation::thread_add_ln96_fu_299_p2() {
    add_ln96_fu_299_p2 = (!zext_ln91_reg_384.read().is_01() || !zext_ln96_2_fu_295_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln91_reg_384.read()) + sc_biguint<6>(zext_ln96_2_fu_295_p1.read()));
}

void Autocorrelation::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void Autocorrelation::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void Autocorrelation::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void Autocorrelation::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void Autocorrelation::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void Autocorrelation::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void Autocorrelation::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void Autocorrelation::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void Autocorrelation::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void Autocorrelation::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void Autocorrelation::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void Autocorrelation::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void Autocorrelation::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void Autocorrelation::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void Autocorrelation::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void Autocorrelation::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void Autocorrelation::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln90_fu_251_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Autocorrelation::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Autocorrelation::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln90_fu_251_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Autocorrelation::thread_bitcast_ln667_fu_356_p1() {
    bitcast_ln667_fu_356_p1 = X_M_imag_load_reg_446.read();
}

void Autocorrelation::thread_grp_fu_173_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_173_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        grp_fu_173_opcode = ap_const_lv2_0;
    } else {
        grp_fu_173_opcode = "XX";
    }
}

void Autocorrelation::thread_grp_fu_173_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_173_p0 = p_r_M_real_reg_150.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        grp_fu_173_p0 = reg_219.read();
    } else {
        grp_fu_173_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_173_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_173_p1 = reg_239.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        grp_fu_173_p1 = reg_224.read();
    } else {
        grp_fu_173_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_177_opcode() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        grp_fu_177_opcode = ap_const_lv2_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        grp_fu_177_opcode = ap_const_lv2_0;
    } else {
        grp_fu_177_opcode = "XX";
    }
}

void Autocorrelation::thread_grp_fu_177_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_177_p0 = p_r_M_imag_reg_138.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        grp_fu_177_p0 = reg_229.read();
    } else {
        grp_fu_177_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_177_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_177_p1 = reg_245.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        grp_fu_177_p1 = reg_234.read();
    } else {
        grp_fu_177_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_183_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_183_p0 = p_r_M_real_17_reg_451.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_183_p0 = p_r_M_real_reg_150.read();
    } else {
        grp_fu_183_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_183_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_183_p1 = p_t_real_reg_440.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_183_p1 = ap_const_lv32_41200000;
    } else {
        grp_fu_183_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_189_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_189_p0 = p_r_M_imag_16_reg_457.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_189_p0 = p_r_M_imag_reg_138.read();
    } else {
        grp_fu_189_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_189_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_189_p1 = p_t_imag_fu_365_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_189_p1 = ap_const_lv32_0;
    } else {
        grp_fu_189_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_195_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_195_p0 = p_r_M_imag_16_reg_457.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_195_p0 = p_r_M_imag_reg_138.read();
    } else {
        grp_fu_195_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_195_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_195_p1 = p_t_real_reg_440.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_195_p1 = ap_const_lv32_41200000;
    } else {
        grp_fu_195_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_201_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_201_p0 = p_r_M_real_17_reg_451.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_201_p0 = p_r_M_real_reg_150.read();
    } else {
        grp_fu_201_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_grp_fu_201_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        grp_fu_201_p1 = p_t_imag_fu_365_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_201_p1 = ap_const_lv32_0;
    } else {
        grp_fu_201_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Autocorrelation::thread_icmp_ln90_fu_251_p2() {
    icmp_ln90_fu_251_p2 = (!x_0_reg_116.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_116.read() == ap_const_lv3_4);
}

void Autocorrelation::thread_icmp_ln91_fu_279_p2() {
    icmp_ln91_fu_279_p2 = (!y_0_reg_127.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_127.read() == ap_const_lv3_4);
}

void Autocorrelation::thread_icmp_ln93_fu_310_p2() {
    icmp_ln93_fu_310_p2 = (!l_0_reg_162.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(l_0_reg_162.read() == ap_const_lv4_A);
}

void Autocorrelation::thread_l_fu_316_p2() {
    l_fu_316_p2 = (!l_0_reg_162.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(l_0_reg_162.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void Autocorrelation::thread_p_t_imag_fu_365_p1() {
    p_t_imag_fu_365_p1 = xor_ln667_fu_359_p2.read();
}

void Autocorrelation::thread_tmp_fu_267_p3() {
    tmp_fu_267_p3 = esl_concat<3,2>(x_0_reg_116.read(), ap_const_lv2_0);
}

void Autocorrelation::thread_tmp_s_fu_322_p3() {
    tmp_s_fu_322_p3 = esl_concat<4,2>(l_0_reg_162.read(), ap_const_lv2_0);
}

void Autocorrelation::thread_x_fu_257_p2() {
    x_fu_257_p2 = (!x_0_reg_116.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(x_0_reg_116.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void Autocorrelation::thread_xor_ln667_fu_359_p2() {
    xor_ln667_fu_359_p2 = (bitcast_ln667_fu_356_p1.read() ^ ap_const_lv32_80000000);
}

void Autocorrelation::thread_y_fu_285_p2() {
    y_fu_285_p2 = (!y_0_reg_127.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(y_0_reg_127.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void Autocorrelation::thread_zext_ln91_fu_275_p1() {
    zext_ln91_fu_275_p1 = esl_zext<6,5>(tmp_fu_267_p3.read());
}

void Autocorrelation::thread_zext_ln94_1_fu_339_p1() {
    zext_ln94_1_fu_339_p1 = esl_zext<64,7>(add_ln94_fu_334_p2.read());
}

void Autocorrelation::thread_zext_ln94_2_fu_350_p1() {
    zext_ln94_2_fu_350_p1 = esl_zext<64,7>(add_ln94_1_fu_345_p2.read());
}

void Autocorrelation::thread_zext_ln94_fu_330_p1() {
    zext_ln94_fu_330_p1 = esl_zext<7,6>(tmp_s_fu_322_p3.read());
}

void Autocorrelation::thread_zext_ln96_1_fu_291_p1() {
    zext_ln96_1_fu_291_p1 = esl_zext<7,3>(y_0_reg_127.read());
}

void Autocorrelation::thread_zext_ln96_2_fu_295_p1() {
    zext_ln96_2_fu_295_p1 = esl_zext<6,3>(y_0_reg_127.read());
}

void Autocorrelation::thread_zext_ln96_3_fu_304_p1() {
    zext_ln96_3_fu_304_p1 = esl_zext<64,6>(add_ln96_fu_299_p2.read());
}

void Autocorrelation::thread_zext_ln96_fu_263_p1() {
    zext_ln96_fu_263_p1 = esl_zext<7,3>(x_0_reg_116.read());
}

void Autocorrelation::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln90_fu_251_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln91_fu_279_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln93_fu_310_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<43>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

