// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "scaled_fixed2ieee.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic scaled_fixed2ieee::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic scaled_fixed2ieee::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state1 = "1";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state2 = "10";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state3 = "100";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state4 = "1000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state5 = "10000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state6 = "100000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> scaled_fixed2ieee::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1 = "1";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_0 = "0";
const sc_lv<1> scaled_fixed2ieee::ap_const_lv1_1 = "1";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_2 = "10";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_4 = "100";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_5 = "101";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_6 = "110";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_0 = "00";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3 = "11";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_1 = "1";
const sc_lv<3> scaled_fixed2ieee::ap_const_lv3_0 = "000";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_3 = "11";
const sc_lv<2> scaled_fixed2ieee::ap_const_lv2_2 = "10";
const sc_lv<4> scaled_fixed2ieee::ap_const_lv4_0 = "0000";
const sc_lv<6> scaled_fixed2ieee::ap_const_lv6_3E = "111110";
const sc_lv<6> scaled_fixed2ieee::ap_const_lv6_2F = "101111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_10 = "10000";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_1F = "11111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3E = "111110";
const sc_lv<63> scaled_fixed2ieee::ap_const_lv63_7FFFFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_F = "1111";
const sc_lv<3> scaled_fixed2ieee::ap_const_lv3_4 = "100";
const sc_lv<3> scaled_fixed2ieee::ap_const_lv3_1 = "1";
const sc_lv<63> scaled_fixed2ieee::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> scaled_fixed2ieee::ap_const_lv12_3FF = "1111111111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_7 = "111";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_A = "1010";
const sc_lv<32> scaled_fixed2ieee::ap_const_lv32_3D = "111101";
const sc_lv<52> scaled_fixed2ieee::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<11> scaled_fixed2ieee::ap_const_lv11_0 = "00000000000";
const sc_lv<64> scaled_fixed2ieee::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const bool scaled_fixed2ieee::ap_const_boolean_1 = true;

scaled_fixed2ieee::scaled_fixed2ieee(sc_module_name name) : sc_module(name), mVcdFile(0) {
    music_mux_42_32_1_1_U197 = new music_mux_42_32_1_1<1,1,32,32,32,32,2,32>("music_mux_42_32_1_1_U197");
    music_mux_42_32_1_1_U197->din0(out_bits_2_V_load_reg_669);
    music_mux_42_32_1_1_U197->din1(out_bits_2_V_1_load_reg_675);
    music_mux_42_32_1_1_U197->din2(out_bits_2_V_2_load_reg_681);
    music_mux_42_32_1_1_U197->din3(p_Result_45_reg_744);
    music_mux_42_32_1_1_U197->din4(p_Val2_59_fu_418_p5);
    music_mux_42_32_1_1_U197->dout(p_Val2_59_fu_418_p6);
    music_mux_42_32_1_1_U198 = new music_mux_42_32_1_1<1,1,32,32,32,32,2,32>("music_mux_42_32_1_1_U198");
    music_mux_42_32_1_1_U198->din0(c_3_1_fu_110);
    music_mux_42_32_1_1_U198->din1(c_3_2_fu_114);
    music_mux_42_32_1_1_U198->din2(c_3_3_fu_118);
    music_mux_42_32_1_1_U198->din3(c_3_fu_106);
    music_mux_42_32_1_1_U198->din4(sh_assign_fu_494_p5);
    music_mux_42_32_1_1_U198->dout(sh_assign_fu_494_p6);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( bitcast_ln512_fu_633_p1 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_bitcast_ln512_fu_633_p1);
    sensitive << ( p_Result_47_fu_623_p4 );

    SC_METHOD(thread_c_0_fu_438_p3);
    sensitive << ( p_Result_46_fu_428_p4 );

    SC_METHOD(thread_empty_fu_593_p1);
    sensitive << ( newexp_fu_574_p2 );

    SC_METHOD(thread_i_3_fu_408_p2);
    sensitive << ( i1_0_reg_157 );

    SC_METHOD(thread_i_4_fu_472_p2);
    sensitive << ( i2_0_reg_190 );

    SC_METHOD(thread_i_fu_236_p2);
    sensitive << ( i_0_reg_134 );

    SC_METHOD(thread_icmp_ln1452_fu_560_p2);
    sensitive << ( in_V );
    sensitive << ( icmp_ln441_reg_765 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln444_fu_555_p2 );

    SC_METHOD(thread_icmp_ln423_fu_230_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_134 );

    SC_METHOD(thread_icmp_ln434_fu_402_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_157 );

    SC_METHOD(thread_icmp_ln441_fu_466_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i2_0_reg_190 );

    SC_METHOD(thread_icmp_ln444_fu_555_p2);
    sensitive << ( icmp_ln441_reg_765 );
    sensitive << ( sh_assign_reg_774 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_icmp_ln566_fu_262_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sub_ln424_fu_250_p2 );
    sensitive << ( icmp_ln423_fu_230_p2 );
    sensitive << ( sub_ln425_fu_256_p2 );

    SC_METHOD(thread_lshr_ln566_1_fu_352_p2);
    sensitive << ( zext_ln566_1_fu_342_p1 );

    SC_METHOD(thread_lshr_ln566_fu_346_p2);
    sensitive << ( select_ln566_1_fu_321_p3 );
    sensitive << ( zext_ln566_fu_338_p1 );

    SC_METHOD(thread_newexp_fu_574_p2);
    sensitive << ( shift_1_reg_211 );
    sensitive << ( sext_ln452_fu_570_p1 );

    SC_METHOD(thread_or_ln453_fu_588_p2);
    sensitive << ( icmp_ln1452_reg_807 );
    sensitive << ( tmp_12_fu_580_p3 );

    SC_METHOD(thread_out_bits_0_V_fu_375_p5);
    sensitive << ( p_Val2_s_reg_146 );
    sensitive << ( tmp_8_fu_368_p3 );

    SC_METHOD(thread_out_exp_V_fu_615_p3);
    sensitive << ( or_ln453_fu_588_p2 );
    sensitive << ( empty_fu_593_p1 );

    SC_METHOD(thread_p_Result_45_fu_285_p5);
    sensitive << ( tmp_6_fu_277_p3 );

    SC_METHOD(thread_p_Result_46_fu_428_p4);
    sensitive << ( p_Val2_59_fu_418_p6 );

    SC_METHOD(thread_p_Result_47_fu_623_p4);
    sensitive << ( out_exp_V_fu_615_p3 );
    sensitive << ( significand_V_fu_607_p3 );

    SC_METHOD(thread_p_Result_s_fu_358_p2);
    sensitive << ( lshr_ln566_fu_346_p2 );
    sensitive << ( lshr_ln566_1_fu_352_p2 );

    SC_METHOD(thread_p_Val2_59_fu_418_p5);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_157 );

    SC_METHOD(thread_phitmp2_fu_597_p4);
    sensitive << ( p_Val2_63_reg_201 );

    SC_METHOD(thread_r_V_42_fu_542_p2);
    sensitive << ( p_0119_0_reg_168 );
    sensitive << ( zext_ln1287_fu_532_p1 );

    SC_METHOD(thread_r_V_44_fu_548_p3);
    sensitive << ( isNeg_reg_781 );
    sensitive << ( r_V_fu_536_p2 );
    sensitive << ( r_V_42_fu_542_p2 );

    SC_METHOD(thread_r_V_fu_536_p2);
    sensitive << ( p_0119_0_reg_168 );
    sensitive << ( zext_ln1287_fu_532_p1 );

    SC_METHOD(thread_select_ln566_1_fu_321_p3);
    sensitive << ( in_V );
    sensitive << ( icmp_ln566_reg_708 );
    sensitive << ( tmp_fu_297_p4 );

    SC_METHOD(thread_select_ln566_2_fu_327_p3);
    sensitive << ( sub_ln425_reg_701 );
    sensitive << ( icmp_ln566_reg_708 );
    sensitive << ( sub_ln566_1_reg_715 );

    SC_METHOD(thread_select_ln566_fu_314_p3);
    sensitive << ( icmp_ln566_reg_708 );
    sensitive << ( sub_ln566_fu_306_p2 );
    sensitive << ( sub_ln566_2_fu_310_p2 );

    SC_METHOD(thread_sext_ln452_fu_570_p1);
    sensitive << ( sub_ln452_fu_565_p2 );

    SC_METHOD(thread_sh_assign_fu_494_p5);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i2_0_reg_190 );

    SC_METHOD(thread_shift_fu_522_p2);
    sensitive << ( sh_assign_reg_774 );
    sensitive << ( shift_0_reg_178 );

    SC_METHOD(thread_shl_ln_fu_242_p3);
    sensitive << ( i_0_reg_134 );

    SC_METHOD(thread_significand_V_fu_607_p3);
    sensitive << ( or_ln453_fu_588_p2 );
    sensitive << ( phitmp2_fu_597_p4 );

    SC_METHOD(thread_sub_ln1311_fu_516_p2);
    sensitive << ( sh_assign_fu_494_p6 );

    SC_METHOD(thread_sub_ln424_fu_250_p2);
    sensitive << ( shl_ln_fu_242_p3 );

    SC_METHOD(thread_sub_ln425_fu_256_p2);
    sensitive << ( shl_ln_fu_242_p3 );

    SC_METHOD(thread_sub_ln452_fu_565_p2);
    sensitive << ( prescale );

    SC_METHOD(thread_sub_ln566_1_fu_268_p2);
    sensitive << ( sub_ln425_fu_256_p2 );

    SC_METHOD(thread_sub_ln566_2_fu_310_p2);
    sensitive << ( sub_ln424_reg_695 );
    sensitive << ( sub_ln425_reg_701 );

    SC_METHOD(thread_sub_ln566_3_fu_332_p2);
    sensitive << ( select_ln566_fu_314_p3 );

    SC_METHOD(thread_sub_ln566_fu_306_p2);
    sensitive << ( sub_ln424_reg_695 );
    sensitive << ( sub_ln425_reg_701 );

    SC_METHOD(thread_tmp_12_fu_580_p3);
    sensitive << ( newexp_fu_574_p2 );

    SC_METHOD(thread_tmp_6_fu_277_p3);
    sensitive << ( trunc_ln566_fu_274_p1 );

    SC_METHOD(thread_tmp_8_fu_368_p3);
    sensitive << ( trunc_ln169_reg_749 );

    SC_METHOD(thread_tmp_fu_297_p4);
    sensitive << ( in_V );

    SC_METHOD(thread_trunc_ln169_fu_364_p1);
    sensitive << ( p_Result_s_fu_358_p2 );

    SC_METHOD(thread_trunc_ln510_fu_414_p1);
    sensitive << ( i1_0_reg_157 );

    SC_METHOD(thread_trunc_ln566_fu_274_p1);
    sensitive << ( in_V );

    SC_METHOD(thread_ush_fu_527_p3);
    sensitive << ( sh_assign_reg_774 );
    sensitive << ( isNeg_reg_781 );
    sensitive << ( sub_ln1311_reg_787 );

    SC_METHOD(thread_zext_ln1287_fu_532_p1);
    sensitive << ( ush_fu_527_p3 );

    SC_METHOD(thread_zext_ln566_1_fu_342_p1);
    sensitive << ( sub_ln566_3_fu_332_p2 );

    SC_METHOD(thread_zext_ln566_fu_338_p1);
    sensitive << ( select_ln566_2_fu_327_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln423_fu_230_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln441_reg_765 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln444_fu_555_p2 );
    sensitive << ( icmp_ln434_fu_402_p2 );

    ap_CS_fsm = "00000001";
    ap_return_preg = "0000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "scaled_fixed2ieee_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_V, "(port)in_V");
    sc_trace(mVcdFile, prescale, "(port)prescale");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, out_bits_2_V_load_reg_669, "out_bits_2_V_load_reg_669");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, out_bits_2_V_1_load_reg_675, "out_bits_2_V_1_load_reg_675");
    sc_trace(mVcdFile, out_bits_2_V_2_load_reg_681, "out_bits_2_V_2_load_reg_681");
    sc_trace(mVcdFile, i_fu_236_p2, "i_fu_236_p2");
    sc_trace(mVcdFile, i_reg_690, "i_reg_690");
    sc_trace(mVcdFile, sub_ln424_fu_250_p2, "sub_ln424_fu_250_p2");
    sc_trace(mVcdFile, sub_ln424_reg_695, "sub_ln424_reg_695");
    sc_trace(mVcdFile, icmp_ln423_fu_230_p2, "icmp_ln423_fu_230_p2");
    sc_trace(mVcdFile, sub_ln425_fu_256_p2, "sub_ln425_fu_256_p2");
    sc_trace(mVcdFile, sub_ln425_reg_701, "sub_ln425_reg_701");
    sc_trace(mVcdFile, icmp_ln566_fu_262_p2, "icmp_ln566_fu_262_p2");
    sc_trace(mVcdFile, icmp_ln566_reg_708, "icmp_ln566_reg_708");
    sc_trace(mVcdFile, sub_ln566_1_fu_268_p2, "sub_ln566_1_fu_268_p2");
    sc_trace(mVcdFile, sub_ln566_1_reg_715, "sub_ln566_1_reg_715");
    sc_trace(mVcdFile, p_Result_45_fu_285_p5, "p_Result_45_fu_285_p5");
    sc_trace(mVcdFile, p_Result_45_reg_744, "p_Result_45_reg_744");
    sc_trace(mVcdFile, trunc_ln169_fu_364_p1, "trunc_ln169_fu_364_p1");
    sc_trace(mVcdFile, trunc_ln169_reg_749, "trunc_ln169_reg_749");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_3_fu_408_p2, "i_3_fu_408_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln441_fu_466_p2, "icmp_ln441_fu_466_p2");
    sc_trace(mVcdFile, icmp_ln441_reg_765, "icmp_ln441_reg_765");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, i_4_fu_472_p2, "i_4_fu_472_p2");
    sc_trace(mVcdFile, i_4_reg_769, "i_4_reg_769");
    sc_trace(mVcdFile, sh_assign_fu_494_p6, "sh_assign_fu_494_p6");
    sc_trace(mVcdFile, sh_assign_reg_774, "sh_assign_reg_774");
    sc_trace(mVcdFile, isNeg_reg_781, "isNeg_reg_781");
    sc_trace(mVcdFile, sub_ln1311_fu_516_p2, "sub_ln1311_fu_516_p2");
    sc_trace(mVcdFile, sub_ln1311_reg_787, "sub_ln1311_reg_787");
    sc_trace(mVcdFile, shift_fu_522_p2, "shift_fu_522_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, r_V_44_fu_548_p3, "r_V_44_fu_548_p3");
    sc_trace(mVcdFile, icmp_ln1452_fu_560_p2, "icmp_ln1452_fu_560_p2");
    sc_trace(mVcdFile, icmp_ln1452_reg_807, "icmp_ln1452_reg_807");
    sc_trace(mVcdFile, icmp_ln444_fu_555_p2, "icmp_ln444_fu_555_p2");
    sc_trace(mVcdFile, i_0_reg_134, "i_0_reg_134");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, p_Val2_s_reg_146, "p_Val2_s_reg_146");
    sc_trace(mVcdFile, i1_0_reg_157, "i1_0_reg_157");
    sc_trace(mVcdFile, icmp_ln434_fu_402_p2, "icmp_ln434_fu_402_p2");
    sc_trace(mVcdFile, p_0119_0_reg_168, "p_0119_0_reg_168");
    sc_trace(mVcdFile, shift_0_reg_178, "shift_0_reg_178");
    sc_trace(mVcdFile, i2_0_reg_190, "i2_0_reg_190");
    sc_trace(mVcdFile, p_Val2_63_reg_201, "p_Val2_63_reg_201");
    sc_trace(mVcdFile, shift_1_reg_211, "shift_1_reg_211");
    sc_trace(mVcdFile, out_bits_2_V_fu_94, "out_bits_2_V_fu_94");
    sc_trace(mVcdFile, out_bits_0_V_fu_375_p5, "out_bits_0_V_fu_375_p5");
    sc_trace(mVcdFile, out_bits_2_V_1_fu_98, "out_bits_2_V_1_fu_98");
    sc_trace(mVcdFile, out_bits_2_V_2_fu_102, "out_bits_2_V_2_fu_102");
    sc_trace(mVcdFile, c_3_fu_106, "c_3_fu_106");
    sc_trace(mVcdFile, c_0_fu_438_p3, "c_0_fu_438_p3");
    sc_trace(mVcdFile, trunc_ln510_fu_414_p1, "trunc_ln510_fu_414_p1");
    sc_trace(mVcdFile, c_3_1_fu_110, "c_3_1_fu_110");
    sc_trace(mVcdFile, c_3_2_fu_114, "c_3_2_fu_114");
    sc_trace(mVcdFile, c_3_3_fu_118, "c_3_3_fu_118");
    sc_trace(mVcdFile, shl_ln_fu_242_p3, "shl_ln_fu_242_p3");
    sc_trace(mVcdFile, trunc_ln566_fu_274_p1, "trunc_ln566_fu_274_p1");
    sc_trace(mVcdFile, tmp_6_fu_277_p3, "tmp_6_fu_277_p3");
    sc_trace(mVcdFile, sub_ln566_fu_306_p2, "sub_ln566_fu_306_p2");
    sc_trace(mVcdFile, sub_ln566_2_fu_310_p2, "sub_ln566_2_fu_310_p2");
    sc_trace(mVcdFile, tmp_fu_297_p4, "tmp_fu_297_p4");
    sc_trace(mVcdFile, select_ln566_fu_314_p3, "select_ln566_fu_314_p3");
    sc_trace(mVcdFile, select_ln566_2_fu_327_p3, "select_ln566_2_fu_327_p3");
    sc_trace(mVcdFile, sub_ln566_3_fu_332_p2, "sub_ln566_3_fu_332_p2");
    sc_trace(mVcdFile, select_ln566_1_fu_321_p3, "select_ln566_1_fu_321_p3");
    sc_trace(mVcdFile, zext_ln566_fu_338_p1, "zext_ln566_fu_338_p1");
    sc_trace(mVcdFile, zext_ln566_1_fu_342_p1, "zext_ln566_1_fu_342_p1");
    sc_trace(mVcdFile, lshr_ln566_fu_346_p2, "lshr_ln566_fu_346_p2");
    sc_trace(mVcdFile, lshr_ln566_1_fu_352_p2, "lshr_ln566_1_fu_352_p2");
    sc_trace(mVcdFile, p_Result_s_fu_358_p2, "p_Result_s_fu_358_p2");
    sc_trace(mVcdFile, tmp_8_fu_368_p3, "tmp_8_fu_368_p3");
    sc_trace(mVcdFile, p_Val2_59_fu_418_p5, "p_Val2_59_fu_418_p5");
    sc_trace(mVcdFile, p_Val2_59_fu_418_p6, "p_Val2_59_fu_418_p6");
    sc_trace(mVcdFile, p_Result_46_fu_428_p4, "p_Result_46_fu_428_p4");
    sc_trace(mVcdFile, sh_assign_fu_494_p5, "sh_assign_fu_494_p5");
    sc_trace(mVcdFile, ush_fu_527_p3, "ush_fu_527_p3");
    sc_trace(mVcdFile, zext_ln1287_fu_532_p1, "zext_ln1287_fu_532_p1");
    sc_trace(mVcdFile, r_V_fu_536_p2, "r_V_fu_536_p2");
    sc_trace(mVcdFile, r_V_42_fu_542_p2, "r_V_42_fu_542_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, sub_ln452_fu_565_p2, "sub_ln452_fu_565_p2");
    sc_trace(mVcdFile, sext_ln452_fu_570_p1, "sext_ln452_fu_570_p1");
    sc_trace(mVcdFile, newexp_fu_574_p2, "newexp_fu_574_p2");
    sc_trace(mVcdFile, tmp_12_fu_580_p3, "tmp_12_fu_580_p3");
    sc_trace(mVcdFile, or_ln453_fu_588_p2, "or_ln453_fu_588_p2");
    sc_trace(mVcdFile, phitmp2_fu_597_p4, "phitmp2_fu_597_p4");
    sc_trace(mVcdFile, empty_fu_593_p1, "empty_fu_593_p1");
    sc_trace(mVcdFile, out_exp_V_fu_615_p3, "out_exp_V_fu_615_p3");
    sc_trace(mVcdFile, significand_V_fu_607_p3, "significand_V_fu_607_p3");
    sc_trace(mVcdFile, p_Result_47_fu_623_p4, "p_Result_47_fu_623_p4");
    sc_trace(mVcdFile, bitcast_ln512_fu_633_p1, "bitcast_ln512_fu_633_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

scaled_fixed2ieee::~scaled_fixed2ieee() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete music_mux_42_32_1_1_U197;
    delete music_mux_42_32_1_1_U198;
}

void scaled_fixed2ieee::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv64_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
            ap_return_preg = bitcast_ln512_fu_633_p1.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln434_fu_402_p2.read()))) {
        i1_0_reg_157 = i_3_fu_408_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln423_fu_230_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_157 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln434_fu_402_p2.read()))) {
        i2_0_reg_190 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln441_reg_765.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln444_fu_555_p2.read()))) {
        i2_0_reg_190 = i_4_reg_769.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_0_reg_134 = i_reg_690.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_134 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln434_fu_402_p2.read()))) {
        p_0119_0_reg_168 = in_V.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln441_reg_765.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln444_fu_555_p2.read()))) {
        p_0119_0_reg_168 = r_V_44_fu_548_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln441_reg_765.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln444_fu_555_p2.read()))) {
        p_Val2_63_reg_201 = r_V_44_fu_548_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln441_fu_466_p2.read()))) {
        p_Val2_63_reg_201 = p_0119_0_reg_168.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if (esl_seteq<1,2,2>(ap_const_lv2_0, i_0_reg_134.read())) {
            p_Val2_s_reg_146 = out_bits_2_V_load_reg_669.read();
        } else if ((!esl_seteq<1,2,2>(ap_const_lv2_0, i_0_reg_134.read()) && 
                    !esl_seteq<1,2,2>(i_0_reg_134.read(), ap_const_lv2_1))) {
            p_Val2_s_reg_146 = out_bits_2_V_2_load_reg_681.read();
        } else if (esl_seteq<1,2,2>(i_0_reg_134.read(), ap_const_lv2_1)) {
            p_Val2_s_reg_146 = out_bits_2_V_1_load_reg_675.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln434_fu_402_p2.read()))) {
        shift_0_reg_178 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln441_reg_765.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln444_fu_555_p2.read()))) {
        shift_0_reg_178 = shift_fu_522_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln441_reg_765.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln444_fu_555_p2.read()))) {
        shift_1_reg_211 = shift_fu_522_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln441_fu_466_p2.read()))) {
        shift_1_reg_211 = shift_0_reg_178.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln434_fu_402_p2.read()) && esl_seteq<1,2,2>(ap_const_lv2_0, trunc_ln510_fu_414_p1.read()))) {
        c_3_1_fu_110 = c_0_fu_438_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln434_fu_402_p2.read()) && esl_seteq<1,2,2>(ap_const_lv2_1, trunc_ln510_fu_414_p1.read()))) {
        c_3_2_fu_114 = c_0_fu_438_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln434_fu_402_p2.read()) && esl_seteq<1,2,2>(trunc_ln510_fu_414_p1.read(), ap_const_lv2_2))) {
        c_3_3_fu_118 = c_0_fu_438_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln434_fu_402_p2.read()) && esl_seteq<1,2,2>(trunc_ln510_fu_414_p1.read(), ap_const_lv2_3))) {
        c_3_fu_106 = c_0_fu_438_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_4_reg_769 = i_4_fu_472_p2.read();
        icmp_ln441_reg_765 = icmp_ln441_fu_466_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_690 = i_fu_236_p2.read();
        out_bits_2_V_1_load_reg_675 = out_bits_2_V_1_fu_98.read();
        out_bits_2_V_2_load_reg_681 = out_bits_2_V_2_fu_102.read();
        out_bits_2_V_load_reg_669 = out_bits_2_V_fu_94.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln444_fu_555_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln441_reg_765.read())))) {
        icmp_ln1452_reg_807 = icmp_ln1452_fu_560_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln423_fu_230_p2.read(), ap_const_lv1_0))) {
        icmp_ln566_reg_708 = icmp_ln566_fu_262_p2.read();
        sub_ln424_reg_695 = sub_ln424_fu_250_p2.read();
        sub_ln425_reg_701 = sub_ln425_fu_256_p2.read();
        sub_ln566_1_reg_715 = sub_ln566_1_fu_268_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln441_fu_466_p2.read()))) {
        isNeg_reg_781 = sh_assign_fu_494_p6.read().range(31, 31);
        sh_assign_reg_774 = sh_assign_fu_494_p6.read();
        sub_ln1311_reg_787 = sub_ln1311_fu_516_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(i_0_reg_134.read(), ap_const_lv2_1))) {
        out_bits_2_V_1_fu_98 = out_bits_0_V_fu_375_p5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && !esl_seteq<1,2,2>(ap_const_lv2_0, i_0_reg_134.read()) && !esl_seteq<1,2,2>(i_0_reg_134.read(), ap_const_lv2_1))) {
        out_bits_2_V_2_fu_102 = out_bits_0_V_fu_375_p5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,2,2>(ap_const_lv2_0, i_0_reg_134.read()))) {
        out_bits_2_V_fu_94 = out_bits_0_V_fu_375_p5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln423_fu_230_p2.read(), ap_const_lv1_1))) {
        p_Result_45_reg_744 = p_Result_45_fu_285_p5.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        trunc_ln169_reg_749 = trunc_ln169_fu_364_p1.read();
    }
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void scaled_fixed2ieee::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void scaled_fixed2ieee::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void scaled_fixed2ieee::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        ap_return = bitcast_ln512_fu_633_p1.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void scaled_fixed2ieee::thread_bitcast_ln512_fu_633_p1() {
    bitcast_ln512_fu_633_p1 = p_Result_47_fu_623_p4.read();
}

void scaled_fixed2ieee::thread_c_0_fu_438_p3() {
    c_0_fu_438_p3 = esl_cttz<32,32>(p_Result_46_fu_428_p4.read());
}

void scaled_fixed2ieee::thread_empty_fu_593_p1() {
    empty_fu_593_p1 = newexp_fu_574_p2.read().range(11-1, 0);
}

void scaled_fixed2ieee::thread_i_3_fu_408_p2() {
    i_3_fu_408_p2 = (!i1_0_reg_157.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i1_0_reg_157.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void scaled_fixed2ieee::thread_i_4_fu_472_p2() {
    i_4_fu_472_p2 = (!i2_0_reg_190.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i2_0_reg_190.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void scaled_fixed2ieee::thread_i_fu_236_p2() {
    i_fu_236_p2 = (!i_0_reg_134.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(i_0_reg_134.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void scaled_fixed2ieee::thread_icmp_ln1452_fu_560_p2() {
    icmp_ln1452_fu_560_p2 = (!in_V.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(in_V.read() == ap_const_lv63_0);
}

void scaled_fixed2ieee::thread_icmp_ln423_fu_230_p2() {
    icmp_ln423_fu_230_p2 = (!i_0_reg_134.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_134.read() == ap_const_lv2_3);
}

void scaled_fixed2ieee::thread_icmp_ln434_fu_402_p2() {
    icmp_ln434_fu_402_p2 = (!i1_0_reg_157.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_157.read() == ap_const_lv3_4);
}

void scaled_fixed2ieee::thread_icmp_ln441_fu_466_p2() {
    icmp_ln441_fu_466_p2 = (!i2_0_reg_190.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i2_0_reg_190.read() == ap_const_lv3_4);
}

void scaled_fixed2ieee::thread_icmp_ln444_fu_555_p2() {
    icmp_ln444_fu_555_p2 = (!sh_assign_reg_774.read().is_01() || !ap_const_lv32_10.is_01())? sc_lv<1>(): sc_lv<1>(sh_assign_reg_774.read() == ap_const_lv32_10);
}

void scaled_fixed2ieee::thread_icmp_ln566_fu_262_p2() {
    icmp_ln566_fu_262_p2 = (!sub_ln425_fu_256_p2.read().is_01() || !sub_ln424_fu_250_p2.read().is_01())? sc_lv<1>(): (sc_biguint<6>(sub_ln425_fu_256_p2.read()) > sc_biguint<6>(sub_ln424_fu_250_p2.read()));
}

void scaled_fixed2ieee::thread_lshr_ln566_1_fu_352_p2() {
    lshr_ln566_1_fu_352_p2 = (!zext_ln566_1_fu_342_p1.read().is_01())? sc_lv<63>(): ap_const_lv63_7FFFFFFFFFFFFFFF >> (unsigned short)zext_ln566_1_fu_342_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_lshr_ln566_fu_346_p2() {
    lshr_ln566_fu_346_p2 = (!zext_ln566_fu_338_p1.read().is_01())? sc_lv<63>(): select_ln566_1_fu_321_p3.read() >> (unsigned short)zext_ln566_fu_338_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_newexp_fu_574_p2() {
    newexp_fu_574_p2 = (!sext_ln452_fu_570_p1.read().is_01() || !shift_1_reg_211.read().is_01())? sc_lv<32>(): (sc_bigint<32>(sext_ln452_fu_570_p1.read()) - sc_biguint<32>(shift_1_reg_211.read()));
}

void scaled_fixed2ieee::thread_or_ln453_fu_588_p2() {
    or_ln453_fu_588_p2 = (tmp_12_fu_580_p3.read() | icmp_ln1452_reg_807.read());
}

void scaled_fixed2ieee::thread_out_bits_0_V_fu_375_p5() {
    out_bits_0_V_fu_375_p5 = esl_partset<32,32,17,32,32>(p_Val2_s_reg_146.read(), tmp_8_fu_368_p3.read(), ap_const_lv32_F, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_out_exp_V_fu_615_p3() {
    out_exp_V_fu_615_p3 = (!or_ln453_fu_588_p2.read()[0].is_01())? sc_lv<11>(): ((or_ln453_fu_588_p2.read()[0].to_bool())? ap_const_lv11_0: empty_fu_593_p1.read());
}

void scaled_fixed2ieee::thread_p_Result_45_fu_285_p5() {
    p_Result_45_fu_285_p5 = esl_partset<32,32,16,32,32>(ap_const_lv32_0, tmp_6_fu_277_p3.read(), ap_const_lv32_10, ap_const_lv32_1F);
}

void scaled_fixed2ieee::thread_p_Result_46_fu_428_p4() {
    p_Result_46_fu_428_p4 = p_Val2_59_fu_418_p6.read().range(0, 31);
}

void scaled_fixed2ieee::thread_p_Result_47_fu_623_p4() {
    p_Result_47_fu_623_p4 = esl_concat<12,52>(esl_concat<1,11>(ap_const_lv1_0, out_exp_V_fu_615_p3.read()), significand_V_fu_607_p3.read());
}

void scaled_fixed2ieee::thread_p_Result_s_fu_358_p2() {
    p_Result_s_fu_358_p2 = (lshr_ln566_fu_346_p2.read() & lshr_ln566_1_fu_352_p2.read());
}

void scaled_fixed2ieee::thread_p_Val2_59_fu_418_p5() {
    p_Val2_59_fu_418_p5 = i1_0_reg_157.read().range(2-1, 0);
}

void scaled_fixed2ieee::thread_phitmp2_fu_597_p4() {
    phitmp2_fu_597_p4 = p_Val2_63_reg_201.read().range(61, 10);
}

void scaled_fixed2ieee::thread_r_V_42_fu_542_p2() {
    r_V_42_fu_542_p2 = (!zext_ln1287_fu_532_p1.read().is_01())? sc_lv<63>(): p_0119_0_reg_168.read() << (unsigned short)zext_ln1287_fu_532_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_r_V_44_fu_548_p3() {
    r_V_44_fu_548_p3 = (!isNeg_reg_781.read()[0].is_01())? sc_lv<63>(): ((isNeg_reg_781.read()[0].to_bool())? r_V_fu_536_p2.read(): r_V_42_fu_542_p2.read());
}

void scaled_fixed2ieee::thread_r_V_fu_536_p2() {
    r_V_fu_536_p2 = (!p_0119_0_reg_168.read().is_01() || !zext_ln1287_fu_532_p1.read().is_01())? sc_lv<63>(): sc_bigint<63>(p_0119_0_reg_168.read()) >> (unsigned short)zext_ln1287_fu_532_p1.read().to_uint();
}

void scaled_fixed2ieee::thread_select_ln566_1_fu_321_p3() {
    select_ln566_1_fu_321_p3 = (!icmp_ln566_reg_708.read()[0].is_01())? sc_lv<63>(): ((icmp_ln566_reg_708.read()[0].to_bool())? tmp_fu_297_p4.read(): in_V.read());
}

void scaled_fixed2ieee::thread_select_ln566_2_fu_327_p3() {
    select_ln566_2_fu_327_p3 = (!icmp_ln566_reg_708.read()[0].is_01())? sc_lv<6>(): ((icmp_ln566_reg_708.read()[0].to_bool())? sub_ln566_1_reg_715.read(): sub_ln425_reg_701.read());
}

void scaled_fixed2ieee::thread_select_ln566_fu_314_p3() {
    select_ln566_fu_314_p3 = (!icmp_ln566_reg_708.read()[0].is_01())? sc_lv<6>(): ((icmp_ln566_reg_708.read()[0].to_bool())? sub_ln566_fu_306_p2.read(): sub_ln566_2_fu_310_p2.read());
}

void scaled_fixed2ieee::thread_sext_ln452_fu_570_p1() {
    sext_ln452_fu_570_p1 = esl_sext<32,12>(sub_ln452_fu_565_p2.read());
}

void scaled_fixed2ieee::thread_sh_assign_fu_494_p5() {
    sh_assign_fu_494_p5 = i2_0_reg_190.read().range(2-1, 0);
}

void scaled_fixed2ieee::thread_shift_fu_522_p2() {
    shift_fu_522_p2 = (!sh_assign_reg_774.read().is_01() || !shift_0_reg_178.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sh_assign_reg_774.read()) + sc_biguint<32>(shift_0_reg_178.read()));
}

void scaled_fixed2ieee::thread_shl_ln_fu_242_p3() {
    shl_ln_fu_242_p3 = esl_concat<2,4>(i_0_reg_134.read(), ap_const_lv4_0);
}

void scaled_fixed2ieee::thread_significand_V_fu_607_p3() {
    significand_V_fu_607_p3 = (!or_ln453_fu_588_p2.read()[0].is_01())? sc_lv<52>(): ((or_ln453_fu_588_p2.read()[0].to_bool())? ap_const_lv52_0: phitmp2_fu_597_p4.read());
}

void scaled_fixed2ieee::thread_sub_ln1311_fu_516_p2() {
    sub_ln1311_fu_516_p2 = (!ap_const_lv32_0.is_01() || !sh_assign_fu_494_p6.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(sh_assign_fu_494_p6.read()));
}

void scaled_fixed2ieee::thread_sub_ln424_fu_250_p2() {
    sub_ln424_fu_250_p2 = (!ap_const_lv6_3E.is_01() || !shl_ln_fu_242_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_3E) - sc_biguint<6>(shl_ln_fu_242_p3.read()));
}

void scaled_fixed2ieee::thread_sub_ln425_fu_256_p2() {
    sub_ln425_fu_256_p2 = (!ap_const_lv6_2F.is_01() || !shl_ln_fu_242_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_2F) - sc_biguint<6>(shl_ln_fu_242_p3.read()));
}

void scaled_fixed2ieee::thread_sub_ln452_fu_565_p2() {
    sub_ln452_fu_565_p2 = (!ap_const_lv12_3FF.is_01() || !prescale.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_3FF) - sc_biguint<12>(prescale.read()));
}

void scaled_fixed2ieee::thread_sub_ln566_1_fu_268_p2() {
    sub_ln566_1_fu_268_p2 = (!ap_const_lv6_3E.is_01() || !sub_ln425_fu_256_p2.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_3E) - sc_biguint<6>(sub_ln425_fu_256_p2.read()));
}

void scaled_fixed2ieee::thread_sub_ln566_2_fu_310_p2() {
    sub_ln566_2_fu_310_p2 = (!sub_ln424_reg_695.read().is_01() || !sub_ln425_reg_701.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln424_reg_695.read()) - sc_biguint<6>(sub_ln425_reg_701.read()));
}

void scaled_fixed2ieee::thread_sub_ln566_3_fu_332_p2() {
    sub_ln566_3_fu_332_p2 = (!ap_const_lv6_3E.is_01() || !select_ln566_fu_314_p3.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_3E) - sc_biguint<6>(select_ln566_fu_314_p3.read()));
}

void scaled_fixed2ieee::thread_sub_ln566_fu_306_p2() {
    sub_ln566_fu_306_p2 = (!sub_ln425_reg_701.read().is_01() || !sub_ln424_reg_695.read().is_01())? sc_lv<6>(): (sc_biguint<6>(sub_ln425_reg_701.read()) - sc_biguint<6>(sub_ln424_reg_695.read()));
}

void scaled_fixed2ieee::thread_tmp_12_fu_580_p3() {
    tmp_12_fu_580_p3 = newexp_fu_574_p2.read().range(31, 31);
}

void scaled_fixed2ieee::thread_tmp_6_fu_277_p3() {
    tmp_6_fu_277_p3 = esl_concat<15,1>(trunc_ln566_fu_274_p1.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_8_fu_368_p3() {
    tmp_8_fu_368_p3 = esl_concat<16,1>(trunc_ln169_reg_749.read(), ap_const_lv1_1);
}

void scaled_fixed2ieee::thread_tmp_fu_297_p4() {
    tmp_fu_297_p4 = in_V.read().range(0, 62);
}

void scaled_fixed2ieee::thread_trunc_ln169_fu_364_p1() {
    trunc_ln169_fu_364_p1 = p_Result_s_fu_358_p2.read().range(16-1, 0);
}

void scaled_fixed2ieee::thread_trunc_ln510_fu_414_p1() {
    trunc_ln510_fu_414_p1 = i1_0_reg_157.read().range(2-1, 0);
}

void scaled_fixed2ieee::thread_trunc_ln566_fu_274_p1() {
    trunc_ln566_fu_274_p1 = in_V.read().range(15-1, 0);
}

void scaled_fixed2ieee::thread_ush_fu_527_p3() {
    ush_fu_527_p3 = (!isNeg_reg_781.read()[0].is_01())? sc_lv<32>(): ((isNeg_reg_781.read()[0].to_bool())? sub_ln1311_reg_787.read(): sh_assign_reg_774.read());
}

void scaled_fixed2ieee::thread_zext_ln1287_fu_532_p1() {
    zext_ln1287_fu_532_p1 = esl_zext<63,32>(ush_fu_527_p3.read());
}

void scaled_fixed2ieee::thread_zext_ln566_1_fu_342_p1() {
    zext_ln566_1_fu_342_p1 = esl_zext<63,6>(sub_ln566_3_fu_332_p2.read());
}

void scaled_fixed2ieee::thread_zext_ln566_fu_338_p1() {
    zext_ln566_fu_338_p1 = esl_zext<63,6>(select_ln566_2_fu_327_p3.read());
}

void scaled_fixed2ieee::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln423_fu_230_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln434_fu_402_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln444_fu_555_p2.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln441_reg_765.read())))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

